--------------------------------------------
-- Game mode type
-- @brief 덱과 스태미나에서 사용하는 스트링 타입의 게임 모드
--------------------------------------------
GAME_MODE = 
{
	ADVENTURE = 'st',
	COLOSSEUM = 'pvp',
}

--------------------------------------------
-- 각종 게임 모드
--------------------------------------------
-- 게임 모드
GAME_MODE_ADVENTURE = 1
GAME_MODE_NEST_DUNGEON = 2
GAME_MODE_SECRET_DUNGEON = 3
GAME_MODE_COLOSSEUM = 4

-- 네스트 던전 하위 던전 모드
NEST_DUNGEON_DRAGON = 1
NEST_DUNGEON_NIGHTMARE = 2
NEST_DUNGEON_TREE = 3

-- 비밀 던전 하위 던전 모드
SECRET_DUNGEON_GOLD = 1
SECRET_DUNGEON_RELATION = 2

--------------------------------------------
-- 인게임 Flow 연출
--------------------------------------------
-- #  드래곤/몬스터 배치 후 흔들림 랜덤 범위(- ~ +)
CHARACTER_FLOATING_MIN_X_SCOPE = 5
CHARACTER_FLOATING_MAX_X_SCOPE = 8
CHARACTER_FLOATING_MIN_Y_SCOPE = 14
CHARACTER_FLOATING_MAX_Y_SCOPE = 20
-- #  드래곤/몬스터 배치 후 흔들림 반복 주기 시간(초)
CHARACTER_FLOATING_TIME = 1

-- # 인게임 Flow 연출 타입 정의 및 상수 테이블 생성
MAP_FLOATING_Y_SCOPE = 1
MAP_FLOATING_TIME = 2
MAP_FLOATING_ROTATE_SCOPE = 3
MAP_FLOATING_ROTATE_TIME = 4
WAVE_INTERMISSION_TIME = 5

IN_GAME_CONSTANTS = {}
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE] = {}
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][1] = {}
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][2] = {}
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][3] = {}
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][4] = {}
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][5] = {}
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][6] = {}
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][99] = {}
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON] = {}
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_DRAGON] = {}
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_NIGHTMARE] = {}
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_TREE] = {}
IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON] = {}
IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_GOLD] = {}
IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_RELATION] = {}
IN_GAME_CONSTANTS[GAME_MODE_COLOSSEUM] = {}

-- # 배경 백판 floating 흔들림 범위(- ~ +)
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][1][MAP_FLOATING_Y_SCOPE] = 6
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][2][MAP_FLOATING_Y_SCOPE] = 6
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][3][MAP_FLOATING_Y_SCOPE] = 6
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][4][MAP_FLOATING_Y_SCOPE] = 6
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][5][MAP_FLOATING_Y_SCOPE] = 6
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][6][MAP_FLOATING_Y_SCOPE] = 6
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][99][MAP_FLOATING_Y_SCOPE] = 6

IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_DRAGON][MAP_FLOATING_Y_SCOPE] = 6
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_NIGHTMARE][MAP_FLOATING_Y_SCOPE] = 6
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_TREE][MAP_FLOATING_Y_SCOPE] = 64

IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_GOLD][MAP_FLOATING_Y_SCOPE] = 6
IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_RELATION][MAP_FLOATING_Y_SCOPE] = 6

IN_GAME_CONSTANTS[GAME_MODE_COLOSSEUM][MAP_FLOATING_Y_SCOPE] = 6

-- # 배경 백판 floating 흔들림 반복 주기 시간(초)
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][1][MAP_FLOATING_TIME] = 3
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][2][MAP_FLOATING_TIME] = 3
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][3][MAP_FLOATING_TIME] = 3
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][4][MAP_FLOATING_TIME] = 3
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][5][MAP_FLOATING_TIME] = 3
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][6][MAP_FLOATING_TIME] = 3
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][99][MAP_FLOATING_TIME] = 3

IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_DRAGON][MAP_FLOATING_TIME] = 3
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_NIGHTMARE][MAP_FLOATING_TIME] = 3
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_TREE][MAP_FLOATING_TIME] = 12

IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_GOLD][MAP_FLOATING_TIME] = 3
IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_RELATION][MAP_FLOATING_TIME] = 3

IN_GAME_CONSTANTS[GAME_MODE_COLOSSEUM][MAP_FLOATING_TIME] = 3

-- # 배경 백판 floating 회전 범위(- ~ +)
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][1][MAP_FLOATING_ROTATE_SCOPE] = 0
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][2][MAP_FLOATING_ROTATE_SCOPE] = 0
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][3][MAP_FLOATING_ROTATE_SCOPE] = 0
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][4][MAP_FLOATING_ROTATE_SCOPE] = 0
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][5][MAP_FLOATING_ROTATE_SCOPE] = 0
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][6][MAP_FLOATING_ROTATE_SCOPE] = 0
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][99][MAP_FLOATING_ROTATE_SCOPE] = 0

IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_DRAGON][MAP_FLOATING_ROTATE_SCOPE] = 0
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_NIGHTMARE][MAP_FLOATING_ROTATE_SCOPE] = 0
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_TREE][MAP_FLOATING_ROTATE_SCOPE] = 5

IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_GOLD][MAP_FLOATING_ROTATE_SCOPE] = 0
IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_RELATION][MAP_FLOATING_ROTATE_SCOPE] = 0

IN_GAME_CONSTANTS[GAME_MODE_COLOSSEUM][MAP_FLOATING_ROTATE_SCOPE] = 0

-- # 배경 백판 floating 회전 반복 주기 시간
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][1][MAP_FLOATING_ROTATE_TIME] = 5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][2][MAP_FLOATING_ROTATE_TIME] = 5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][3][MAP_FLOATING_ROTATE_TIME] = 5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][4][MAP_FLOATING_ROTATE_TIME] = 5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][5][MAP_FLOATING_ROTATE_TIME] = 5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][6][MAP_FLOATING_ROTATE_TIME] = 5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][99][MAP_FLOATING_ROTATE_TIME] = 5

IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_DRAGON][MAP_FLOATING_ROTATE_TIME] = 5
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_NIGHTMARE][MAP_FLOATING_ROTATE_TIME] = 5
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_TREE][MAP_FLOATING_ROTATE_TIME] = 10

IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_GOLD][MAP_FLOATING_ROTATE_TIME] = 5
IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_RELATION][MAP_FLOATING_ROTATE_TIME] = 5

IN_GAME_CONSTANTS[GAME_MODE_COLOSSEUM][MAP_FLOATING_ROTATE_TIME] = 5

-- # 웨이브 인터미션 시간
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][1][WAVE_INTERMISSION_TIME] = 1.5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][2][WAVE_INTERMISSION_TIME] = 1.5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][3][WAVE_INTERMISSION_TIME] = 1.5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][4][WAVE_INTERMISSION_TIME] = 1.5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][5][WAVE_INTERMISSION_TIME] = 1.5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][6][WAVE_INTERMISSION_TIME] = 1.5
IN_GAME_CONSTANTS[GAME_MODE_ADVENTURE][99][WAVE_INTERMISSION_TIME] = 1.5

IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_DRAGON][WAVE_INTERMISSION_TIME] = 1.5
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_NIGHTMARE][WAVE_INTERMISSION_TIME] = 1.5
IN_GAME_CONSTANTS[GAME_MODE_NEST_DUNGEON][NEST_DUNGEON_TREE][WAVE_INTERMISSION_TIME] = 2

IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_GOLD][WAVE_INTERMISSION_TIME] = 1.5
IN_GAME_CONSTANTS[GAME_MODE_SECRET_DUNGEON][SECRET_DUNGEON_RELATION][WAVE_INTERMISSION_TIME] = 1.5


IN_GAME_CONSTANTS[GAME_MODE_COLOSSEUM][WAVE_INTERMISSION_TIME] = 1.5

--------------------------------------------
function getInGameConstant(type)
    local ret = 0

    local gameMode = g_gameScene.m_gameMode
	
    -- 모험모드
    if gameMode == GAME_MODE_ADVENTURE then
        local difficulty, chapter, stage = parseAdventureID(g_gameScene.m_stageID)
		
        ret = IN_GAME_CONSTANTS[gameMode][chapter][type]

    -- 네스트 던전
    elseif gameMode == GAME_MODE_NEST_DUNGEON then
        local t_dungeon = g_nestDungeonData:parseNestDungeonID(g_gameScene.m_stageID)
        local dungeonMode = t_dungeon['dungeon_mode']

        ret = IN_GAME_CONSTANTS[gameMode][dungeonMode][type]

    -- 비밀 던전
    elseif gameMode == GAME_MODE_SECRET_DUNGEON then
        local t_dungeon = g_secretDungeonData:parseSecretDungeonID(g_gameScene.m_stageID)
        local dungeonMode = t_dungeon['dungeon_mode']

        ret = IN_GAME_CONSTANTS[gameMode][dungeonMode][type]

    -- 콜로세움
    elseif gameMode == GAME_MODE_COLOSSEUM then
        ret = IN_GAME_CONSTANTS[gameMode][type]
    end
    
    return ret
end