local t_module = {
    'Cocos2d',
    'Cocos2dConstants',
    'lib/net',
    'lib/class',
    'lib/utils',
    'lib/StringUtils',
    'lib/Translate',
    'lib/scheduler',
    'lib/SocketTCP',
    'lib/math',
    'lib/Radian',
    'uilib/UIManager',
    'uilib/UI',
    'uilib/UILoader',
    'uilib/TableView',
    'uilib/Notification',
    'perpleLib/StringUtils',
    'perpleLib/sn',
    'perpleLib/crand',
    'perpleLib/PerpleScene',
    'perpleLib/PerpleScene',
    'fixed_constant',
    'SoundMgr',
    'SoundMgrController',
    'SoundMgrProtected',
    'PatchData',
    'PatchCore',
    'Coroutine',
	'LocalPushMgr',

	-- CONSTANT 
    'Constant',
	'ConstantGameMode',
    'ConstantDragonEvolution',
    'ConstantDragonGrade',
    'ConstantAttribute',
    'ConstantString',
    'ConstantStatusEffect',
    'ConstantColosseum',

    -- Data클래스
    'ColosseumUserInfo',
    		
    -- Struct
    'StructEventPopupTab',
    'StructAdventureChapterAchieveInfo',
    'StructAdventureStageInfo',
    'StructCalendarDay',
    'StructAttendanceData',
    'StructExchangeProductData',
    'StructRuneObject',
    'StructRuneSetObject',
    'StructDragonObject',
    'StructSlimeObject',
    'StructFriendshipObject',
	'StructStatusEffect',
    'StructIndividualStatus',
    'StructFreeDragonSummonInfo',
    'StructQuestData',
    'StructCollectionData',
    'StructDragonUnit',
    'StructDragonUnitCondition',
    'StructUserInfo',

	-- ServerData
    'ServerData',
    'ServerData_User',
	'ServerData_Tamer',
    'ServerData_Dragons',
    'ServerData_Slimes',
    'ServerData_DragonUnit',
    'ServerData_Deck',
    'ServerData_Staminas',
    'ServerData_Adventure',
    'ServerData_AdventureFirstReward',
    'ServerData_NestDungeon',
    'ServerData_SecretDungeon',
    'ServerData_AncientTower',
    'ServerData_Stage',
    'ServerData_LobbyUserList',
    'ServerData_AutoPlaySetting',
    'ServerData_Runes',
	'ServerData_Quest',
    'ServerData_Colosseum',
    'ServerData_ColosseumRank',
    'ServerData_Inventory',
    'ServerData_Friend',
	'ServerData_Shop',
    'ServerData_Mail',
    'ServerData_Item',
    'ServerData_Gacha',
    'ServerData_Attendance',
    'ServerData_Birthday',
    'ServerData_Exchange',
    'ServerData_Exploration',
    'ServerData_HotTime',
    'ServerData_Collection',
    'ServerData_Event',
    'ServerData_DragonSummon',
    'ServerData_Highlight',
	'ServerData_Ranking',
	'ServerData_Formation',

    -- Util
    'Action',
    'TimeLib',
    'Table',
    'TableClass',
    'SecurityNumber',
    'ResPreloadHelper',
    'ResPreloadMgr',
    'RichLabel',
    'NumberLabel',
	'NumberLabel_Pumping',
    'FpsMeter',
    'LevelupDirector',
    'LevelupDirector_GameResult',
    'MapManager',
    'LocalData',
    'ChatIgnoreList',
    'UserData',
	'ConstantData',
    'CollisionHelper',
    'DropHelper',
    'DragonAutoSetHelper',
    'DragonSkillBonusHelper',
    'DragonSkillManager',
    'DragonSkillIndivisualInfo',
    'FriendBuffManager',
    'SumRandom',
    'ValidationAssistant',
    'Counter',
    'Stopwatch',
    'Camera',
    'CameraTouchHandler',
    'CameraTouchHandler_Lobby',
    'SwipeGesture',
    'ValidationDragon',
    'TableViewExtension',
	'SkillHelper',
	'SkillTargetFinder',
    'StatusEffectHelper',
    'AreaOfEffectHelper',
    'ShaderCache',
    'SortManager',
    'SortManager_Rune',
    'SortManager_Fruit',
    'SortManager_EvolutionStone',
    'SortManager_Dragon',
    'DragonSortManager',
    'RuneEnchantHelper',
    'SimplePrimitivesDraw',
    'Util_BuffStringParser',
	'StageMissionMgr',
	'LogRecorder',
	'LogRecorderWorld',
	'LogRecorderChar',
    'UINavigator',
    'RenderTextureBatchNode',
	'IconHelper',
    'ResHelper',
    'AnimatorHelper',
	'SensitivityHelper',
	'MailHelper',
	'BattleStatisticsHelper',

    'ChatClient',
    'ChatManager',
    'ChatContent',
    'ChatContentList',
    'BroadcastMgr',

    -- Table
    'TableStageDesc',
    'TableDragon',
    'TableDragonType',
    'TableDragonExp',
    'TableDragonSkill',
    'TableDragonSkillBonus',
    'TableMonster',
    'TableMonsterHitPos',
	'TableMonsterSkill',
    'TableEnemyMove',
    'TableFriendship',
    'TableFriendshipVariables',
    'TableFriendBuff',
    'TableFruit',
    'TableUserLevel',
    'TableReqGold',
    'TableLactea',
    'TableDragonResearch',
    'TableDrop',
    'TableTamer',
	'TableTamerSkill',
    'TableGradeInfo',
    'TableEvolutionInfo',
    'TableStatus',
    'TableFormation',
    'TableRuneSet',
    'TableRuneGrade',
    'TableRuneMoptStatus',
    'TableItem',
    'TableItemRand',
	'TableQuest',
	'TableShop',
    'TableSecretDungeon',
    'TableColosseumReward',
    'TableDragonUnit',
    'TableStageMission',
    'TableCalendar',
    'TableOption',
    'TableDropIngame',
    'TableStaminaInfo',
    'TableScenarioResource',
    'TableDragonPhrase',
    'TableSlime',
    'TableSlimeExp',
	'TableLoadingGuide',
    'TableExchange',

    -- Interface
    'IEventDispatcher',
	'IEventListener',
    'IHighlight',
    'IStateHelper',
    'ITopUserInfo_EventListener',
    'ITabUI',
	'ISkillMultiAttack',

    -- Scene
    'SceneCommon',
    'SceneLogo',
    'ScenePatch',
    'SceneTitle',
    'SceneLobby',
    'SceneDV',
    'SceneGame',
    'SceneGameColosseum',
    'SceneAdventure',
    'SceneNestDungeon',
    'SceneSecretDungeon',
    'SceneColosseum',
    'SceneAncientTower',

    -- Phys
	'PhysWorld',
    'PhysObject',

	-- Animator
    'Animator',
    'AnimatorPng',
    'AnimatorSpine',
    'AnimatorVrp',

	-- Entity GameWorld
    'Entity',
    'GameWorld',
    'GameWorldColosseum',
    'GameWorld_Touch',
    'GameWorld_Formation',
    'GameWorld_Unit',
    'GameWorld_Gold',
    'GameState',
    'GameState_AncientTower',
    'GameState_NestDungeon',
    'GameState_NestDungeon_Dragon',
    'GameState_NestDungeon_Nightmare',
    'GameState_NestDungeon_Tree',
    'GameState_NestDungeon_Gold',
    'GameState_SecretDungeon_Relation',
    'GameState_Colosseum',
    'GameAuto',
    'GameAuto_Hero',
    'GameAuto_Enemy',
    'GameCoolTime',
    'GameDragonSkill',
    'GameCamera',
    'GameTimeScale',
    'GameHighlightMgr',
    'DropItemMgr',
	'ShakeManager',
    
	-- CARRIER
	'ActivityCarrier',
	'EventCarrier',
	
    -- MAP
    'ScrollMap',
    'ScrollMapLayer',
    'AnimationMap',
    	
	-- MISSILE
	'Missile',
    'MissileBoomerang',
    'MissileCurve',
    'MissileDrop',
    'MissileDropGuid',
    'MissileDropRandom',
    'MissileDropTarget',
    'MissileDropZigzag',
    'MissileGuid',
    'MissileGuidTarget',
    'MissileTarget',
    'MissileZigzag',
    'MissileEffecter',
    'MissileLua',
    'MissileBounce',
    'MissileFix',
    'require_MissileLua',
    'LaserMissile',
	'MissileGuide',

	-- CHARACTER
	'Character',
    'CharacterEvent',
    'CharacterState',
    'CharacterSkill',
    'CharacterStateDelegate',
    'Dragon',
    'Monster',
    'MonsterLua_Boss',
    'Monster_GiantDragon',
    'Monster_GoldDragon',
    'Monster_Tree',
	'Monster_WorldOrderMachine',
    'Monster_DarkNix',
    'Tamer',
	'TamerSkill',
    'require_EnemyLua',
    'EnemyAppear',
    'EnemyMovementMgr',
    'MissileFactory',
    'MissileLauncher',
    
	-- COMMON MISSILE (공통탄)
	'CommonMissile',
	'CommonMissile_Straight',
	'CommonMissile_Guide',
	'CommonMissile_Cruise',
	'CommonMissile_Shotgun',
	'CommonMissile_Release',
	'CommonMissile_High',
	'CommonMissile_Bounce',
	'CommonMissile_Multi',

    -- ITEM
    'DropItem',

	-- STATUS EFFECT
	'StatusEffect',
    'StatusEffect_Trigger',
	'StatusEffect_Trigger_Release',
	'StatusEffect_Heal',
	'StatusEffect_AddDmg',
	'StatusEffect_DotDmg',
	'StatusEffect_DotDmg_Bleed',
	'StatusEffect_DotDmg_Burn',
	'StatusEffect_DotDmg_Poison',
    'StatusEffect_Protection',
	'StatusEffect_Resist',
	'StatusEffect_Silence',
	'StatusEffect_AttributeChange',
	'StatusEffect_Dispell',

	'StatusEffectIcon',

	-- EFFECT
	'EffectLink',
    'EffectLinearDot',
    'EffectBezierLink',
	'EffectHeal',
    'EffectMotionStreak',
    
	-- SKILL HELPER
	'SkillHitEffectDirector',

    -- SKILL    
	'Skill',
    'SkillLaser',
	'SkillChainLightning',
	'SkillThrowBuff',
    'SkillGuardian',
    'SkillHealSingle',
    'SkillShield',
    'SkillMeleeHack',
	'SkillHealAround',
	'SkillAoERound',
	'SkillAoERound_Sura',
    'SkillAoESquare',
    'SkillAoESquare_Height',
	'SkillAoESquare_Width',
	'SkillAoESquare_Charge',
	'SkillAoESquare_Wonder',
	'SkillAoECone',
	'SkillAoECone_Crash',
	'SkillAoEWedge',
    'SkillLeafBlade',
    'SkillSummon',
    'SkillSpatter',
	'SkillLeap',
	'SkillExplosion',
	'SkillRolling',
	'SkillConditionalAddEffect',
	'SkillCounterAttack',
	'SkillSpiderWeb',
    'SkillHeartOfRuin',
	'SkillBurst',
	'SkillFieldCheck',
	'SkillVoltesX',
	'SkillCharge',
	'SkillRush',
	'SkillContinuous',
    'SkillRapidShot',
	'SkillRapidShot_AddAttack',
	'SkillEnumrate',
	'SkillEnumrate_Curve',
	'SkillEnumrate_Normal',
	'SkillEnumrate_Penetration',

    -- SKILL INDICATOR
    'SkillIndicatorMgr',
    'SkillIndicator',
    'SkillIndicator_Laser',
    'SkillIndicator_Target',
    'SkillIndicator_LeafBlade',
	'SkillIndicator_AoERound',
	'SkillIndicator_AoESquare',
    'SkillIndicator_AoESquare_Height',
    'SkillIndicator_AoESquare_Width',
	'SkillIndicator_AoESquare_Multi',
	'SkillIndicator_AoECone',
	'SkillIndicator_AoEWedge',
	'SkillIndicator_X',
	'SkillIndicator_Penetration',

	'WaveMgr',
    'WaveMgr_SecretRelation',
    'WaveMgr_Colosseum',
    'DynamicWave',
	
	-- 인게임 Util
    'DamageCalc',
    'FormationMgr',
    'FormationMgr_TargetRule',
    'StatusCalculator',
    'StatusCalculatorFormula',
    'DragonCard',
    'TriggerHpPercent',
    'TriggerTime',
    'EffectTimer',

    -- UIC (UI Component)
    'UIC_Node',
    'UIC_Button',
    'UIC_CheckBox',
    'UIC_ClippingNode',
    'UIC_TableViewProtocol',
    'UIC_TableView',
    'UIC_ChatView',
    'UIC_TableViewCell',
    'UIC_TableViewTD',
    'UIC_ChatTableView',
    'UIC_ChatTableViewCell',
    'UIC_RadioButton',
    'UIC_LabelTTF',
    'UIC_RichLabel',
    'UIC_RichLabelCore',
    'UIC_TabManager',
    'UIC_SortList',
    'UIC_Factory',
    'UIC_IndivisualStats',
    'UIC_DragonAnimator',
    'UIC_DragonAnimatorDirector',

	-- UI : 분류 없음
    'UI_BlockPopup',
    'UI_Network',
    'UI_NetworkLoading',
    'UI_TitleScene',
    'UI_TitleSceneLoading',
	'UI_LoadingGuide',
	'UI_LoadingGuide_Patch',
    'UI_Lobby',
    'LobbyMapSpotMgr',
    'LobbyMap',
    'LobbyCharacter',
    'LobbyTamer',
    'LobbyTamerBot',
    'LobbyDragon',
    'LobbyShadow',
    'LobbyUserStatusUI',
    'UI_RewardListPopup',
    'UI_Popup',
    'UI_SimplePopup',
	'UI_ConfirmPopup',
	'UI_ErrorPopup',
    'UI_SimpleDragonInfoPopup',
    'UI_DragonSummon',
    'UI_DragonSummonListItem',
	'UI_ToastPopup',
    'UI_SecretFindPopup',
    'UI_Tooltip',
    'UI_Tooltip_Buff',
	'UI_Tooltip_Indicator',
    'UI_Tooltip_Skill',
    'UI_TopUserInfo',
    'UI_ShopPopup',
	'UI_ShopListItem',
    'UI_ItemCard',
    'UI_RuneCard',
	'UI_RewardCard',
    'UI_SkillCard',
    'UI_DragonSkillCard',
    'UI_GachaResult_Dragon',
    'UI_GuidePopup',
    'UI_NestDungeonScene',
    'UI_NestDungeonListItem',
    'UI_NestDungeonStageListItem',
    'UI_SecretDungeonScene',
    'UI_SecretDungeonStageListItem',
    'UI_EditBoxPopup',
    'UI_SimpleEditBoxPopup',
    'UI_MonsterCard',
    'UI_FruitFeedPress',
    'UI_LobbyUserInfoPopup',
    'UI_UserDeckInfoPopup',
    'UI_DungeonMenu',
    'UI_BattleMenu',
	'UI_QuestPopup',
    'UI_QuestListItem',
    'UI_MailPopup',
    'UI_MailListItem',
    'UI_AcquisitionRegionInformation',
    'UI_AcquisitionRegionListItem',
    'UI_NotificationInfoElement',
    'UI_NotificationInfo',
    'UI_FriendPointGachaPopup',
    'UI_FriendPointGachaResult',
    'UI_GachaBox',
    'UI_ItemInfoPopup',
    'UI_ChapterAchieveRewardPopup',
    'UI_NotificationFullInventoryPopup',
    'UI_DragonInfoBoard',
    'UI_ScenarioPlayer',
    'UI_ScenarioPlayer_Character',
    'UI_ScenarioPlayer_Talk',
	'UI_FormationPopup',
	'UI_FormationListItem',
	'UI_FormationEnhance',
    'UI_UserInfoMini',

	-- UI : 모험
    'UI_AdventureSceneNew',
    'UI_AdventureChapterSelectPopup',
    'UI_AdventureChapterButton',
    'UI_AdventureStageButton',
    'UI_AdventureFirstRewardPopup',
    'UI_AdventureFirstRewardButton',
    'UI_AdventureStageInfo',
    'UI_AdventureStageMissionInfo',
    
	-- UI : 모험 준비
	'UI_ReadyScene',
    'UI_ReadyScene_Deck',
	
	-- UI : 전투 통계
	'UI_StatisticsPopup',
	'UI_StatisticsListItem',

	-- UI : 콜로세움
    'UI_Colosseum',
	'UI_ColosseumRewardPopup',
    'UI_ColosseumReadyScene',
    'UI_ColosseumLoading',
    'UI_ColosseumResult',
    'UI_ColosseumRankListItem',
    'UI_ColosseumFriendRankListItem',
    'UI_ColosseumRewardListItem',
    'UI_ColosseumFirstRewardListItem',
    'UI_ColosseumRankingReward',
    'UI_ColosseumFirstReward',

	-- UI : 고대의 탑
    'UI_AncientTowerScene',
    'UI_AncientTowerListItem',
    'UI_AncientTowerSweepReward',

	-- UI : 인게임
	'UI_Game',
	'UI_GameTamer',
    'UI_GameColosseum',
    'UI_GameResultNew',
    'UI_GameResult_Adventure',
    'UI_GameResult_AncientTower',
    'UI_GameResult_NestDungeon',
    'UI_GameResult_SecretDungeon',
    'UI_GamePause',
    'UI_GamePause_AncientTower',
    'UI_GamePause_NestDungeon',
    'UI_GamePause_SecretDungeon',
    'UI_GamePause_Colosseum',
	'UI_GameDPSPopup',
	'UI_GameDPSListItem',
    'UI_GameDebug',
	'UI_GameDebug_RealTime',
    'UI_IngameDragonPanel',
    'UI_IngameDragonPanelItem',
    'UI_IngameUnitInfo',
    'UI_IngameDragonInfo',
    'UI_IngameBossInfo',
    'UI_AutoPlaySettingPopup',

	-- UI : 인벤토리
    'UI_Inventory',
    'UI_InventorySelectSellItems',
    'UI_InventoryTab',
    'UI_InventoryTabRune',
    'UI_InventoryTabFruit',
    'UI_InventoryTabEvolutionStone',
    'UI_InventoryTabTicket',
    'UI_InventorySellItems',
    'UI_RuneBulkSalePopup',

	-- UI : 각종 랭킹
    'UI_RecommendedDragonInfoPopup',
	'UI_RecommendedDragonInfoListItem_Dungeon',
	'UI_RecommendedDragonInfoListItem_Dragon',
	'UI_RecommendedDragonInfoListItem_Party',
	'UI_OverallRankingPopup',
	'UI_OverallRankingListItem',

    -- UI : 도감 관련
    'UI_Collection',
    'UI_CollectionDetailPopup',
    'UI_CollectionDragonCard',
    'UI_CollectionPointReward',
    'UI_CollectionPointRewardListItem',
    'UI_CollectionRelationPointDraw',
    'UI_CollectionUnitListItem',
    'UI_CollectionTabUnit',
    'UI_CollectionTabDragon',
    'UI_CollectionStoryPopup',
    'UI_CollectionStoryPopup_ApplyTeamTab',
    'UI_CollectionStoryPopup_AllTeamTab',
    'UI_CollectionStoryPopup_DragonTeamTab',
    'UI_CollectionStoryPopupItem',
    'UI_CollectionStoryPopupApplyItem',

    -- UI : 친구 시스템 관련
    'UI_FriendPopup',
    'UI_FriendPopupTab',
    'UI_FriendPopupTabFriends',
    'UI_FriendPopupTabRecommend',
    'UI_FriendPopupTabRequest',
    'UI_FriendPopupTabInvite',
    'UI_FriendPopupTabSupport',
    'UI_FriendListItem',
    'UI_FriendRecommendUserListItem',
    'UI_FriendRequestListItem',
    'UI_FriendSupportListItem',
    'UI_FriendDragonSupportRequestPopup',
    'UI_FriendDragonSupportPopup',
    -- UI : 친구 드래곤 선택
    'UI_FriendSelectPopup',
    'UI_FriendSelectListItem',

    -- UI : 드래곤 관리 관련
    'UI_DragonManage_Base',
    'UI_DragonManageInfo',
    'UI_DragonLevelUp',
    'UI_DragonLevelUpHelper',
    'UI_DragonUpgradeNew',
    'UI_DragonEclvupNew',
    'UI_DragonResearch',
    'UI_DragonManagementEvolution',
    'UI_DragonManageFriendshipResult',
    'UI_CharacterCard',
    'UI_SkillDetailPopup',
    'UI_SkillDetailPopupListItem',
    'UI_DragonGoodbye',   
    'UI_LobbyObject', 
    'UI_DragonRunes',
    'UI_DragonRunesEnhance',
    'UI_DragonFriendship',
    'UI_DragonEvolutionResult',
    'UI_DragonUpgradeResult',
    'UI_DragonEclvResult',
    'UI_DragonLevelupResult',

	-- UI : 테이머 관리
	'UI_TamerManagePopup',
    'UI_TamerManageItem',
	'UI_SkillDetailPopup_Tamer',
    'UI_SkillDetailPopupListItem_Tamer',
	'UI_SkillEnhance',

	-- UI : 출석 이벤트
    'UI_AttendanceBasicListItem',
    'UI_AttendanceSpecialListItem',

    -- UI : 탐험(exploration)
    'UI_Exploration',
    'UI_ExplorationIng',
    'UI_ExplorationLocationButton',
    'UI_ExplorationReady',
    'UI_ExplorationResultPopup',

    -- UI : EVENT
    'UI_EventPopup',
    'UI_EventPopupTabButton',
    'UI_EventPopupTab_Birthday',
    'UI_EventPopupTab_Attendance',
    'UI_EventPopupTab_EventAttendance',
    'UI_EventPopupTab_Exchange',
    'UI_BirthdayCalendarDayElement',
    'UI_BirthdayRewardSelectPopup',
    'UI_BirthdayRewardSelectListItem',
    'UI_ExchangeProductListItem',

	-- UI : 채팅
	'UI_ChatPopup',
    'UI_ChatPopup_WhisperTab',
    'UI_ChatList',
    'UI_ChatListItem',
    'UI_ChatListItem_msg',
    'UI_ChatListItem_myMsg',
    'UI_ChatListItem_systemMsg',
    'UI_ChatIgnoreListItem',

	-- UI : 설정
	'UI_Setting',
    'UI_SettingAccountTab',
    'UI_SettingAlarmTab',
    'UI_SettingDevTab',
    'UI_SettingGameTab',
    'UI_SettingInfoTab',
    'UI_DragonDevApiPopup',
    'UI_InvenDevApiPopup',

    -- Network
    'Network',
    'NetworkLocalServer',
}

-------------------------------------
-- function loadModule
-------------------------------------
function loadModule()
	-- penlight lua 라이브러리
    pl = require'pl.import_into'()

    for i,v in ipairs(t_module) do
        require(v)
    end

    require 'socket'
end

-------------------------------------
-- function reloadModule
-------------------------------------
function reloadModule()
    print('#############################')
    print('## reloadModule() start    ##')

    -- 서버에서 받아서 저장 중인 테이블 백업
    local t_backup_server_table = TABLE:backupServerTable()

    for i,v in ipairs(t_module) do
        if (v ~= 'SoundMgr') and (v ~= 'uilib/UIManager') and (v ~= 'uilib/UILoader')
            and (v ~= 'uilib/TableView') then
            package.loaded[v] = nil
            require(v)
        end
    end

    TABLE:init()

    -- 서버에서 받아서 저장 중인 테이블 적용
    for i,v in pairs(t_backup_server_table) do
        TABLE[i] = v
    end
    print('## reloadModule() end      ##')
    print('#############################')
end