-- 패치 시점에서도 반드시 필요한 루아 모듈은 
-- 하단의 loadModuleForPatchScene에도 추가 해주세요

-- @mskim 2020.08.22
-- 특정 위치, 시기에 제한적으로 사용되는 특히 이벤트와 같은 것들은 사용직전에 require 하도록 한다.

-- @mskim 2020.08.31
-- reload module를 수정하기 편하도록 상단으로 테이블 위치 이동
local t_reload_modules = 
{
    'UI_VideoMaker',
    'UI_GachaResult_Dragon',
    'UIC_DragonAnimatorDirector_Summon',
    'UI_CapsuleBox',
    'UI_DiceEvent',
    'UI_EventPopupTab_PurchaseDaily',
    'UI_EventLFBag',
    'UI_EventLFBagRankingPopup',
}

local t_module = {
    'Cocos2d',
    'Cocos2dConstants',
    'lib/net',
    'lib/class',
    'lib/utils',
    'lib/FormatSIPrefix',
    'StructLanguage',
    'lib/Translate',
    'lib/scheduler',
    'lib/SocketTCP',
    'lib/math',
    'lib/Radian',
    'uilib/UIManager',
    'uilib/UI',
    'uilib/UILoader',
    'uilib/TableView',
    'uilib/Notification',
    'uilib/NotificationBroadcast',
    'perpleLib/StringUtils',
    'perpleLib/sn',
    'perpleLib/crand',
    'perpleLib/PerpleScene',
    'LuaBridge',
	'Global',
    'SoundMgr',
    'SoundMgrController',
    'SoundMgrProtected',
    'PatchData',
    'PatchCore',
    'PatchChecker',
    'ApkExpansion',
    'Coroutine',
	'LocalPushMgr',
    'Analytics',
    'NaverCafeManager',
	'PerpleSdkManager',
	'PaymentHelper',
    'ScriptCache',
    'CppFunctions',
    --'UnityAdsManager',
    --'FacebookAudienceNetworkManager',
    'IAdModule',
    'AdMob',
    'AdManager',
    'AdWithoutPlayManager',
    'XorCipher',
    'PackageManager',
    'UserStatusAnalyser',
    'FullPopupManager',
    'ServerListData',
    'ExperationTime',

	-- CONSTANT 
    'Constant',
    'ConstantUrl',
	'ConstantGameMode',
    'ConstantDragonEvolution',
    'ConstantDragonGrade',
    'ConstantAttribute',
    'ConstantString',
    'ConstantStatusEffect',
    'ConstantColosseum',
    'ConstantColor',
    'ConstantDifficulty',

    -- Struct
    'Structure',
    'StructEventPopupTab',
    'StructAdventureChapterAchieveInfo',
    'StructAdventureStageInfo',
    'StructCalendarDay',
    'StructAttendanceData',
    'StructExchangeProductData',
    'StructRuneObject',
    'StructRuneSetObject',
    'StructRuneCombine',
    'StructDragonObject',
    'StructDragonSkin',
    'StructUpgradeMaterialCombine',
    'StructSlimeObject',
    'StructFriendshipObject',
	'StructReinforcement',
	'StructStatusEffect',
    'StructIndividualStatus',
    'StructFreeDragonSummonInfo',
    'StructQuestData',
    'StructUserInfo',
    'StructUserInfoFriend',
    'StructUserInfoColosseum',
    'StructUserInfoAncientTower',
    'StructUserInfoClan',
    'StructUserInfoClanRaid',
    'StructUserInfoArena',
    'StructUserInfoArenaNew',
	'StructUserInfoClanWar',
    'StructWaveRegenGroup',
    'StructCollisionData',
	'StructBookData',
    'StructAncientTowerFloorData',
    'StructAttrTowerFloorData',
    'StructPickup',
    'StructPackageBundle',
    'StructProduct',
    'StructIAPProduct',
    'StructIAPPurchase',
    'StructProductSubscription',
    'StructMarketProduct',
    'StructLobbyNotice',
    'StructMail',
    'StructFevertime',
    'StructSubscribedInfo',
    'StructHighbrowProduct',
    'StructTamerCostume',
    'StructClan',
    'StructClanMark',
    'StructClanRank',
    'StructClanRaid',
	'StructClanBuff',
    'StructEventDiceInfo',
    'StructEventBingoInfo',
    'StructEventIllusion',
	'StructDailyMission',
	'StructCapsuleBox',
	'StructCapsuleBoxReward',
    'StructCapsuleBoxSchedule',
    'StructTeamBonus',
    'StructRandomShopItem',
    'StructEventMatchCard',
    'StructEventMandragoraQuest',
    'StructAiSkillInfo',
    'StructDeck', -- 덱(팀) 정보를 관리하는 구조체
    'StructTabUI',
    'StructRankReward',
    'StructArenaNewRankReward',
	'StructClanWarLeagueItem',
    'StructClanWarLeague',
    'StructClanWarTournament',
    'StructClanWarMatchItem',
    'StructClanWarMatch',
    'StructPackageState',
    'StructBattlePassInfo',
    'StructDragonPkgData',
    'StructRecall',
    'StructPresetDeck',
    'StructIndivPass',
    'StructRunePreset',
    'StructRunePresetGroup',
    'StructLairStat',

	-- ServerData 
    'ServerData',
    'ServerData_User',
	'ServerData_Tamer',
    'ServerData_TamerCostume',
    'ServerData_Dragons',
    'ServerData_DragonSkin',
    'ServerData_Slimes',
    'ServerData_Deck',
    'ServerData_Staminas',
    'ServerData_Adventure',
    'ServerData_AdventureFirstReward',
    'ServerData_NestDungeon',
    'ServerData_SecretDungeon',
    'ServerData_AncientTower',
    'ServerData_Stage',
    'ServerData_AutoPlaySetting',
    'ServerData_Runes',
	'ServerData_Quest',
    'ServerData_Inventory',
    'ServerData_Friend',
	'ServerData_Shop',
    'ServerData_IAP',
    'ServerData_Subscription',
    'ServerData_LobbyNotice',
    'ServerData_Mail',
    'ServerData_Item',
    'ServerData_Attendance',
    'ServerData_FirstPurchaseEvent',
    'ServerData_PurchasePoint',
    'ServerData_PurchaseDaily',
    'ServerData_Exchange',
    'ServerData_EventBingo',
    'ServerData_EventRuneFestival',
    'ServerData_Exploration',
    'ServerData_HotTime',
    'ServerData_Fevertime',
    'ServerData_Event',
    'ServerData_EventDice',
    'ServerData_ExchangeEvent',
    'ServerData_Highlight',
	'ServerData_Ranking',
	'ServerData_DragonPickRate',
	'ServerData_Formation',
    'ServerData_FormationArena',
	'ServerData_DragonBoard',
    'ServerData_Eggs',
    'ServerData_Hatchery',
    'ServerData_StartTamer',
	'ServerData_Book',
    'ServerData_Colosseum',
    'ServerData_AccessTime',
    'ServerData_MasterRoad',
    'ServerData_ContentLock',
    'ServerData_AutoItemPick',
    'ServerData_Tutorial',
    'ServerData_Highbrow',
    'ServerData_Advertising',
    'ServerData_Roulette',
    'ServerData_EvolutionStone',
    'ServerData_FriendMatch',
    'ServerData_Clan',
    'ServerData_ClanRank',
    'ServerData_ClanRaid',
    'ServerData_LevelUpPackage',
    'ServerData_AdventureBreakthroughPackage',
    'ServerData_AdventureClearPackage',
    'ServerData_AdventureClearPackage02',
    'ServerData_AdventureClearPackage03',
    'ServerData_DailyMission',
	'ServerData_CapsuleBox',
	'ServerData_AttrTower',
    'ServerData_DragonDiary',
    'ServerData_EventGoldDungeon',
    'ServerData_Season',
    'ServerData_AncientRuin',
    'ServerData_RandomShop',
    'ServerData_Arena',
    'ServerData_ArenaNew',
    'ServerData_GrandArena',
    'ServerData_EventMatchCard',
    'ServerData_EventMandragoraQuest',
    'ServerData_EventAlphabet', -- 알파벳 이벤트
    'ServerData_ChallengeMode', -- 챌린지 모드
    'ServerData_SpotSale', -- 깜짝 할인 상품
    'ServerData_EventAdvent', -- 깜짝 출현 이벤트
    'Serverdata_IllusionDungeon', -- 환상 던전 이벤트
    'ServerData_RemoteConfig', -- 원격 설정
    'ServerData_ClanWar',
	'ServerData_ClanWar_Date',
    'ServerData_Supply',
    'ServerData_NewcomerShop',
    'ServerData_FleaShop',
    'ServerData_EventImageQuiz',
    'ServerData_Personalpack',
    'ServerData_EventLFBag',
    'ServerData_AttrTowerPackage',
    'ServerData_EventIncarnationOfSins', -- 죄악의 화신 토벌작전
    'ServerData_RuneMemo', -- 룬 메모
    'ServerData_Dmgate', -- 시련(차원문)
	'ServerData_EventRoulette', -- 어린이날 룰렛 이벤트
    'ServerData_DmgatePackage',
    'ServerData_EventArenaPlay',    -- 콜로세움 참여 이벤트
    'ServerData_EventLeagueRaidPlay',    -- 레이드 참여 이벤트
    'ServerData_LeagueRaid',
    'ServerData_HighbrowVip', -- 하이브로 VIP
    'ServerData_GetDragonPackage',
    'ServerData_ClanRaidEarthPackage',
    'ServerData_ClanRaidWaterPackage',
    'ServerData_ClanRaidFirePackage',
    'ServerData_ClanRaidLightPackage',
    'ServerData_ClanRaidDarkPackage',
    'ServerData_StoryDungeonEvent',
    'ServerData_EventVote',
    'ServerData_EventPopularityGacha',
    'ServerData_RuneGuardian', -- 룬 수호자 클리어 정보
    'ServerData_DeckPreset', -- 프리셋 덱
    'ServerData_IndivPass', -- 개인 패스
    'ServerData_RunePreset', -- 룬 프리셋
    'ServerData_Lair', -- 라테아

    -- Interface
    'IEventDispatcher',
	'IEventListener',
    'IHighlight',
    'IStateHelper',
    'ICharacterBinding',
    'ICharacterStatusEffect',
    'ITopUserInfo_EventListener',
    'ITabUI',
	'ISkillMultiAttack',
    'ISkillSound',

    -- Util
    'SDKManager',
	'ErrorTracker',
    'Action',
    'ServerTime',
    'TimeLib',
    'Table',
    'TableClass',
    'SecurityNumber',
    'ResPreloadMgr',
    'NumberLabel',
    'NumberLabelWithSpriteFrame',
	'NumberLabel_Pumping',
    'FpsMeter',
    'LevelupDirector',
    'LevelupDirector_GameResult',
    'MapManager',
    'LocalData',
    'SettingData',
    'SettingData_Deck',
    'ChatMacroData',
    'LobbyGuideData',
    'LobbyGuideAbstract',
    'LobbyGuide_CapsuleBox',
    'LobbyGuide_Adventure',
    'LobbyGuide_WeeklyShop',
    'LobbyGuide_Colosseum',
    'LobbyGuide_AncientTower',
    'LobbyGuide_AttrTower',
    'LobbyGuide_Arena',
    'LobbyPopupData',
    'LobbyPopupAbstract',
    'LobbyPopup_PackageStep',
    'LobbyPopup_PackageStep2',
    'LobbyPopup_PackageStepOld',
    'LobbyPopup_PurchasePoint',
    'LobbyChangeMgr',
    'ChatIgnoreList',
    'ScenarioViewingHistory',
	'ConstantData',
    'CollisionHelper',
    'DropHelper',
    'DragonAutoSetHelper',
    'DragonAutoSetHelperNew',
    'DragonSkillBonusHelper',
    'DragonSkillManager',
    'DragonSkillIndivisualInfo',
    'DragonSkillIndivisualInfoInGame',
    'DragonSkillCore',
    'DragonGuideNavigator',
    'SumRandom',
	'NumberLoop',
    'ValidationAssistant',
    'Counter',
    'Stopwatch',
    'Camera',
    'CameraTouchHandler',
    'CameraTouchHandler_Lobby',
    'SwipeGesture',
    'ValidationDragon',
    'EquationHelper',
	'SkillHelper',
	'SkillTargetFinder',
    'StatusEffectHelper',
    'AreaOfEffectHelper',
    'TeamBonusHelper',
    'TeamBonusCardFactory',
    'ShaderCache',
    'SortManager',
    'SortManager_Rune',
    'SortManager_Fruit',
    'SortManager_EvolutionStone',
    'SortManager_Transform',
    'SortManager_Dragon',
    'SortManager_Dragon_Illusion',
    'SortManager_Friend',
    'SortManager_ClanMember',
    'SortManager_ClanRequest',
    'SortManager_TeamBonus',
    'SimplePrimitivesDraw',
	'StageMissionMgr',
	'LogRecorder',
	'LogRecorderWorld',
	'LogRecorderChar',
    'UINavigatorDefinition',
    'UINavigator',
    'RenderTextureBatchNode',
    'AncientTowerScoreCalc',
    'IllusionScoreCalc',
	'MultiDeckMgr',
    'MultiDeckMgr_Raid',
    'MatchCardPlayer',
    'WorkListHelper',
    'WorkUnit',

	'DragonInfoIconHelper',
	'IconHelper',
    'ResHelper',
    'AnimatorHelper',
	'SensitivityHelper',
	'MailHelper',
	'BattleStatisticsHelper',
	'UIHelper',
    'QuickLinkHelper',
    'GoogleHelper',
    'MasteryHelper',
    'LoginHelper',

    'ChatClientSocket',
    'ChatManager',
    'ChatManagerClan',
    'ChatContent',
    'ChatContentList',
    'BroadcastMgr',

    -- Table
    'TableStageDesc',
    'TableDragon',
    'TableDragonType',
    'TableDragonSkin',
    'TableDragonExp',
	'TableDragonReinforce',
    'TableDragonSkill',
	'TableDragonSkillModify',
    'TableMonster',
    'TableMonsterHitPos',
	'TableMonsterSkill',
    'TableEnemyMove',
    'TableFriendship',
    'TableFriendshipVariables',
    'TableFriendBuff',
    'TableFruit',
    'TableUserLevel',
    'TableReqGold',
    'TableDrop',
    'TableTamer',
	'TableTamerSkill',
    'TableTamerTitle',
    'TableTamerCostume',
    'TableGradeInfo',
    'TableEvolutionInfo',
    'TableStatus',
    'TableFormation',
    'TableFormationArena',
    'TableRuneSet',
    'TableRuneGrade',
    'TableRuneMoptStatus',
    'TableItem',
    'TableItemType',
    'TableItemRand',
	'TableQuest',
	'TableMasterRoad',
    'TableDragonDiary',
    'TableSecretDungeon',
    'TableStageMission',
    'TableCalendar',
    'TableOption',
    'TableStaminaInfo',
    'TableScenarioResource',
    'TableDragonPhrase',
    'TableSlime',
    'TableSlimeExp',
	'TableLoadingGuide',
    'TableExchange',
    'TableDragonCombine',
    'TableStatusEffect',
    'TableExplorationList',
    'TableColosseumBuff',
	'TableColosseumWinReward',
    'TableStageData',
    'TableHelp',
    'TableGoogleQuest',
    'TableSummonGacha',
    'TableUILocation',
    'TableHighbrow',
    'TableSkillSound',
    'TableEvolutionItemCombine',
    'TablePackageBundle',
    'TableBattlePass',
    'TableClanMark',
	'TableClanMarkCustom',
	'TableDailyMission',
	'TablePickDragon',
    'TableTeamBonus',
    'TableDragonTransform',
    'TableMasterySkill',
    'TableArenaWinReward',
    'TableCollectionReward',
    'TableMastery', -- 특성 테이블
    'TableAlphabetEvent', -- 알파벳 이벤트
    'TableSpotSale',
    'TableSupply',
    'TableFevertime', -- 핫타임
    'TablePersonalpack',
    'TableSummonObject',
    'TableBanWord',
    'TablePackageAchievement',
    'TableRune', -- 룬
    'TableStoryDungeonEvent', -- 스토리 던전 이벤트 테이블
    'TableItemDisplay', -- 아이템 표시 대체용 테이블
    'TableEventQuest', -- 이벤트 퀘스트
    'TablePickupSchedule', -- 픽업 스케쥴
    'TableRuneFilterPoint', -- 룬 필터 포인트
    'TableIndivPass', -- 개인 패스
    'TableIndivPassReward', -- 개인 패스 보상 테이블
    'TableLairBuff', -- 축복 (컬렉션)
    'TableLairBuffStatus', -- 축복 돌림판 능력치 (컬렉션)
    'TableLairCondition', -- 축복 등록 조건
    'TableLairSchedule', -- 축복 시즌
    'TableLanguageConfig', -- 언어 코드

    -- Scene
    'SceneCommon',
    'SceneLogo',
    'ScenePatch',
    'SceneTitle',
    'SceneLobby',
    'SceneDV',
    'SceneGame',
    'SceneGameColosseum',
    'SceneGameArena',
    'SceneGameArenaNew',
    'SceneGameChallengeMode',
    'SceneGameIntro',
    'SceneGameClanRaid',
    'SceneGameEventArena',
    'SceneAdventure',
    'SceneNestDungeon',
    'SceneSecretDungeon',
    'SceneGameIllusion',
    'SceneRuneGuardianDungeon',
    'SceneGameClanWar',
    'SceneDmgate',

    -- Phys
	'PhysWorld',
    'PhysObject',

	-- Animator
    'Animator',
    'AnimatorPng',
    'AnimatorSpine',
    'AnimatorVrp',
    'SpineCacheManager',

	-- Entity GameWorld
    'Entity',
    'GameWorld',
    'GameWorld_Unit',
    'GameWorld_Gold',
	'GameWorld_KeyEvent',
    'GameWorldForDoubleTeam',
    'GameWorldForDoubleTeam_Unit',
    'GameWorldColosseum',
    'GameWorldArena',
    'GameWorldArenaNew',
    'GameWorldIntro',
    'GameWorldClanRaid',
    'GameWorldEventArena',
    'GameWorld_Illusion',
    'GameState',
    'GameState_AncientRuin',
    'GameState_AncientTower',
    'GameState_NestDungeon',
    'GameState_NestDungeon_Dragon',
    'GameState_NestDungeon_Nightmare',
    'GameState_NestDungeon_Tree',
    'GameState_NestDungeon_Gold',
    'GameState_NestDungeon_Jewel',
    'GameState_SecretDungeon_Relation',
    'GameState_Colosseum',
    'GameState_Arena',
    'GameState_ArenaNew',
    'GameState_Intro',
    'GameState_EventGold',
    'GameState_EventArena',
    'GameState_ClanRaid',
    'GameState_ChallengeMode',
    'GameState_RuneGuardianDungeon',
    'GameState_Illusion',
    'GameState_ClanWar',
    'GameState_Dmgate',
    'GameState_LeagueRaid',
    'GameState_StoryDungeonEvent',
    'GameAuto',
    'GameAuto_Hero',
    'GameAuto_Enemy',
    'GameCoolTime',
    'GameMana',
    'GameActiveSkillMgr',
    'GameDragonSkill',
    'GameUnitGroup',
    'GameCamera',
    'GameTimeScale',
    'GameHighlightMgr',
    'GameEnrageDirector',
    'DropItemMgr',
    'DropItemMgr_EventGold',
    'DropItemMgr_Intro',
	'ShakeManager',
    'BenchmarkManager',
    
	-- CARRIER
	'ActivityCarrier',
	'EventCarrier',
	
    -- MAP
    'ScrollMap',
    'ScrollMapLayer',
    'AnimationMap',
    	
	-- MISSILE
	'Missile',
    'MissileGuid',
    'MissileGuidTarget',
    'MissileTarget',
    'MissileZigzag',
    'MissileEffecter',
    'MissileLua',
    'MissileBounce',
    'MissileFix',
    'require_MissileLua',
	'MissileGuide',

	-- CHARACTER
	'Character',
    'CharacterEvent',
    'CharacterState',
    'CharacterSkill',
    'CharacterStateDelegate',
    'Dragon',
    'DragonState',
    'Monster',
    'MonsterLua_Boss',
    'MonsterLua_BossUseDeadMotion',
    'Monster_GiantDragon',
    'Monster_GiantMandragora',
    'Monster_GoldDragon',
    'Monster_Tree',
	'Monster_WorldOrderMachine',
    'Monster_DarkNix',
    'Monster_DarkNixIntro',
    'Monster_ClanRaidBoss',
    'Monster_AncientRuinDragon',
    'Monster_AncientRuinDragonBodyPart',
    'SummonedCreature',
    'Tamer',
	'TamerSkill',
    'require_EnemyLua',
    'EnemyAppear',
    'EnemyMovementMgr',
    'MissileFactory',
    'MissileLauncher',
    
	-- COMMON MISSILE (공통탄)
	'CommonMissile',
	'CommonMissile_Straight',
	'CommonMissile_Guide',
	'CommonMissile_Cruise',
	'CommonMissile_Shotgun',
	'CommonMissile_Release',
	'CommonMissile_High',
	'CommonMissile_Bounce',
	'CommonMissile_Multi',

    -- COMMON Summoning Skill
    'CommonSummoning',

    -- ITEM
    'DropItem',

	-- STATUS EFFECT
	'StatusEffect',
    'StatusEffectUnit',
    'StatusEffectUnit_AddDmg',
    'StatusEffectUnit_AddDmgOneTime',
    'StatusEffectUnit_AddHeal',
    'StatusEffectUnit_Dot',
    'StatusEffectUnit_Dot_Damage',
    'StatusEffectUnit_Dot_Heal',
    'StatusEffectUnit_ConditionalBuff',
    'StatusEffectUnit_ResurrectByTime',

    'StatusEffect_AddDmgOneTime',
	'StatusEffect_Sleep',
    'StatusEffect_Bleed',
    'StatusEffect_Poison',
    'StatusEffect_Protection',
	'StatusEffect_Silence',
	'StatusEffect_AttributeChange',
	'StatusEffect_Dispell',
    'StatusEffect_Zombie',
    'StatusEffect_Immortal',
    'StatusEffect_Immune',
    'StatusEffect_Modify',
    'StatusEffect_SkillModify',
    'StatusEffect_AddMana',
    'StatusEffect_ManaReduce',
    'StatusEffect_Resurrect',
    'StatusEffect_Transfer',
    'StatusEffect_ConditionalBuff',
    'StatusEffect_ConsumeToMissile',
    'StatusEffect_ConditionalModify',
    'StatusEffect_AccelMana',
    'StatusEffect_ProtectionByTime',
    'StatusEffect_SkillCoolReduce',
    'StatusEffect_ClanRaidBoss',

    'StatusEffectEdgeDirector',
	'StatusEffectIcon',

	-- EFFECT
	'EffectLink',
    'EffectGuard',
    'EffectLinearDot',
    'EffectBezierLink',
	'EffectHeal',
    'EffectMotionStreak',
    
	-- SKILL HELPER
	'SkillHitEffectDirector',

    -- SKILL    
	'Skill',
    'SkillLaser',
    'SkillLaser_Darknix',
    'SkillLaser_Zet',
    'SkillLaser_Simple',
	'SkillChainLightning',
	'SkillBeam',
	'SkillThrowBuff',
    'SkillGuardian',
    'SkillMeleeHack',
    'SkillAoECross',
	'SkillAoERound',
	'SkillAoERound_Sura',
    'SkillAoERound_Throw',
    'SkillAoERound_Hide',
    'SkillAoERound_Melee',
    'SkillAoESquare',
    'SkillAoESquare_Height',
    'SkillAoESquare_Height_Top',
	'SkillAoESquare_Width',
    'SkillAoESquare_Width_Right',
	'SkillAoESquare_Charge',
	'SkillAoESquare_Wonder',
	'SkillAoECone',
	'SkillAoECone_Crash',
	'SkillAoEWedge',
    'SkillLeafBlade',
    'SkillSummon',
    'SkillTransform',
    'SkillSpatter',
    'SkillCross',
	'SkillLeap',
	'SkillExplosion',
    'SkillSuicideExplosion',
	'SkillRolling',
	'SkillCounterAttack',
	'SkillSpiderWeb',
    'SkillHeartOfRuin',
	'SkillBurst',
	'SkillFieldCheck',
	'SkillVoltesX',
	'SkillCharge',
	'SkillRush',
    'SkillRapidShot',
	'SkillRapidShot_AddAttack',
	'SkillEnumrate',
	'SkillEnumrate_Curve',
	'SkillEnumrate_Normal',
	'SkillEnumrate_Penetration',
    'SkillEnumrate_Release',
    'SkillBind',
    'SkillRandom',
    'SkillMetamorphosis',
    'SkillLaserBomb',
    'SkillScript',
    'SkillScript_AncientDragon',
    'SkillScript_ClanRaidBoss',
    'SkillScript_ClanRaidBossFinish',
    'SkillScript_Illusion',
    'SkillScript_Charging',
    'SkillScript_Groggy',

    'SkillHealSingle',
    'SkillHealLine',
    'SkillHealAround',
    'SkillHealAoERound',
    'SkillHealAoESquare_Height',
    'SkillHealAoESquare_Width',
    'SkillResurrect',

    'SkillTamerArena',

    -- SKILL INDICATOR
    'SkillIndicatorMgr',
    'SkillIndicatorMgr_Intro',
    'SkillIndicatorMgr_ClanRaid',
    'SkillIndicator',
    'SkillIndicator_Laser',
    'SkillIndicator_Target',
    'SkillIndicator_LeafBlade',
	'SkillIndicator_AoERound',
	'SkillIndicator_AoESquare',
    'SkillIndicator_AoESquare_Height',
    'SkillIndicator_AoESquare_Height_Top',
    'SkillIndicator_AoESquare_Height_Touch',
    'SkillIndicator_AoESquare_Width',
    'SkillIndicator_AoESquare_Width_Right',
    'SkillIndicator_AoESquare_Width_Touch',
	'SkillIndicator_AoESquare_Multi',
	'SkillIndicator_AoECone',
	'SkillIndicator_AoEWedge',
	'SkillIndicator_X',
	'SkillIndicator_Penetration',
    'SkillIndicator_Cross',

	'WaveMgr',
    'WaveMgr_AncientTower',
    'WaveMgr_SecretRelation',
    'WaveMgr_ClanRaid',
    'WaveMgr_Colosseum',
    'WaveMgr_Arena',
    'DynamicWave',
	
	-- 인게임 Util
    'DamageCalc',
    'FormationMgr',
    'FormationMgr_TargetRule',
    'StatusCalculator',
    'StatusCalculatorFormula',
    'TriggerHpPercent',
    'TriggerTime',

    -- UIC (UI Component)
    'UIC_Node',
    'UIC_Button',
    'UIC_CheckBox',
    'UIC_ClippingNode',
    'UIC_TableViewProtocol',
    'UIC_TableView',
    'UIC_ChatView',
    'UIC_TableViewCell',
    'UIC_RankListItem',
    'UIC_TableViewTD',
    'UIC_ChatTableView',
    'UIC_ChatTableViewCell',
    'UIC_RadioButton',
    'UIC_LabelTTF',
    'UIC_RichLabel',
    'UIC_RichLabelCore',
    'UIC_TabManager',
    'UIC_SortList',
    'UIC_SortListTD',
    'UIC_Factory',
    'UIC_IndivisualStats',
    'UIC_DragonAnimator',
    'UIC_DragonAnimatorDirector',
	'UIC_DragonAnimatorDirector_Summon',
    'UIC_ScrollLabel',
    'UIC_BroadcastLabel',
    'UIC_EggPicker',
    'UIC_ExtendedUI',
    'UIC_ScrollButton',
	'UIC_LobbyGuide',
    'UIC_AlarmClockIcon',
    'UIC_RankingList',
    'UIC_ListExpansion',
    'UIC_ListExpansionItem',
	'UIC_ExtendList',
	'UIC_ExtendList_Image',
    'UIC_IconAndName',
    'UIC_Label_TypingEffect',
    'UIC_ArenaRankingList',
	
    -- UI : CARD
    'UI_Card',
    'UI_CharacterCard',
    'UI_RelationCard',
    'UI_ReinforcePointCard',
    'UI_ItemCard',
    'UI_RuneCard',
    'UI_RuneCardOption',
    'UI_RuneCardDragon',
    'UI_MonsterCard',
    'UI_MonsterCustomCard',
	'UI_RewardCard',
    'UI_DragonSkillCard',
    'UI_MonsterSkillCard',
    'UI_TamerSkillCard',

	-- UI : 분류 없음
    'UI_Proceeding',
    'UI_BlockPopup',
    'UI_BlockSplashPopup',
    'UI_Network',
    'UI_NetworkLoading',
    'UI_TitleScene',
    'UI_TitleSceneLoading',
    'UI_Loading',
    'UI_LoadingAdLoad',
	'UI_LoadingGuide',
	'UI_LoadingGuide_Patch',
    'UI_LoadingArena',
    'UI_LoadingArenaNew',
    'UI_Lobby',
    'UI_LobbyLeftTopBtnManager',
    'UI_ManagedButton',
    'UI_ButtonPaymentShop',
    'UI_ButtonFirstPurchaseReward',
    'UI_ButtonSpotSale',
    'UI_ButtonPersonalpack',
    'UI_ButtonSpecialOfferProduct',
    'UI_ButtonSpecialOfferProductGold',
    'UI_ButtonSpecialOfferProductNurture',
    'UI_ButtonSpecialOfferWeidel',
    'UI_ButtonSpecialPeriod',
    'UI_ButtonSupplyDepot',
    'UI_ButtonNewcomerShop',
    'UI_ButtonFleaShop',
    'UI_ButtonBattlePassIndiv',
    'UI_DragonInfoListItem',
    'LobbyMapSpotMgr',
    'LobbyMap',
    'LobbyMapFactory',
    'LobbyMapFactory_clan',
    'LobbyWorldAdapter',
    'LobbyCharacter',
    'LobbyTamer',
    'LobbyTamerBot',
    'LobbyDragon',
    'LobbyShadow',
    'LobbyUserStatusUI',
    'LobbyManager',
    'LobbyManager_Clan',
    'StructToast',
    'ToastManager',
    'UI_RewardListPopup',
    'UI_Popup',
    'UI_SimplePopup',
    'UI_SimplePopup2',
    'UI_SimplePopup3',
	'UI_ConfirmPopup',
	'UI_ObtainPopup',
    'UI_ObtainToastPopup',
    'UI_CheersPopup',
	'UI_EggPopup',
    'UI_EggPopupHundred',
	'UI_BundlePopup',
    'UI_BundlePopupNew',
    'UI_BundlePopupBtnPress',
    'UI_CntBtnPress',
	'UI_ErrorPopup',
    'UI_ErrorPopup_Live',
    'UI_SimpleDragonInfoPopup',
    'UI_SimpleMonsterInfoPopup',
    'UI_Hatchery',
    'UI_HatcheryCombineTab',
    'UI_HatcheryCombinePopup',
    'UI_HatcheryCombineItem',
    'UI_HatcherySummonTab',
    'UI_HatcheryIncubateTab',
    'UI_HatcheryRelationTab',
    'UI_HatcheryRelationItem',
    'UI_RuneForge',
    'UI_RuneForgeInfoTab',
    'UI_RuneForgeManageTab',
    'UI_RuneForgePresetTab',
    'UI_RuneForgeCombineTab',
    'UI_RuneForgeGachaTicketTab',
    'UI_RuneForgeCombineItem',
    'UI_RuneForgeGachaTab',
    'UI_RuneForgeGachaInfo',
	'UI_ToastPopup',
    'UI_SecretFindPopup',
    'UI_Tooltip',
	'UI_Tooltip_Indicator',
    'UI_Tooltip_Skill',
    'UI_TopUserInfo',
    'UI_GoodsInfo',
    'UI_StaminaInfo',
    'UI_StaminaChargePopup',
    'UI_RuneAutoSellAgreePopup',
    'UI_ValorCostumeInfoPopup', -- 용맹 코스튬 안내(구매) 팝업
    'UI_LobbyBanner',
    'UI_AttendanceLobbyBanner',
    'UI_BannerChallengeMode',
	'UI_BannerClanWarAttacking',
    'UI_BannerGrandArena',
    'UI_BannerIllusion',
    'UI_BannerHallOfFame',

    'UI_AdRewardPopup',
    'UI_GachaResult_Dragon100',
    'UI_GachaResult_Dragon',
    'UI_GachaResult_Rune',
	'UI_PickDragonWithRate',
	'UI_PickDragon',
    'UI_DragonAppear',
    'UI_GuidePopup',
    'UI_TabUI_AutoGeneration',
    'UI_HelpClanDungeonSummary',
    'UI_HelpClanDungeonReward',
    'UI_HelpContentsListItem',
    'UI_HelpContents',
    'UI_NestDungeonScene',
    'UI_NestDungeonListItem',
	'UI_NestDungeonSelectingListItem',
    'UI_NestDungeonStageListItem',
    'UI_IllusionStageListItem',
    'UI_NightmareStageListItem',
    'UI_AncientRuinStageListItem',
    'UI_SecretDungeonScene',
    'UI_SecretDungeonListItem',
    'UI_SecretDungeonStageListItem',
    'UI_SimpleEditBoxPopup',
    'UI_FruitFeedPress',
    'UI_UserDeckInfoPopup',
    'UI_UserDeckInfoPopupNew',
    'UI_BattleMenu',
    'UI_BattleMenuItem',
    'UI_BattleMenuItem_Adventure',
    'UI_BattleMenuItem_Dungeon',
    'UI_BattleMenuItem_Competition',
    'UI_BattleMenuItem_Clan',
	'UI_QuestPopup',
    'UI_QuestListItem',
    'UI_QuestListItem_Contents',
	'UI_MasterRoadPopup',
    'UI_MasterRoadPopup_Link',
    'UI_MasterRoadRewardPopup',
    'UI_MasterRoadRewardPopupNew',
    'UI_MailPopup',
    'UI_MailListItem',
    'UI_MailRewardPopup',
    'UI_MailSelectPopup',
    'UI_AcquisitionRegionInformation',
    'UI_AcquisitionRegionListItem',
    'UI_NotificationInfoElement',
    'UI_NotificationInfo',
    'UI_ItemInfoPopup',
    'UI_ChapterAchieveRewardPopup',
    'UI_NotificationFullInventoryPopup',
    'UI_DragonInfoBoard',
    'UI_MonsterInfoBoard',
	'UI_FormationPopup',
	'UI_FormationListItem',
    'UI_FormationArenaPopup',
	'UI_FormationArenaListItem',
    'UI_UserInfoMini',
    'UI_UserLevelUp',
    'UI_ContentLock',
    'UI_ChangeNickPopup',
    'UI_LoginPopup',
    'UI_LoginPopup2',
    'UI_LoginPopupWithoutFirebase',
    'UI_LoginIntegratePopup',
    'UI_WebView',
    'UI_Help',
    'UI_HelpClan',
    'UI_HelpRune',
    'UI_HelpGrandArena',
    'UI_HelpDragonGuidePopup',
    'UI_GuidePopup_PurchasePoint',
    'UI_DragonGoodbyeResult',
    'UI_QuickPopupNew',
    'UI_CouponPopup',
    'UI_CouponPopup_Confirm',
    'UI_CouponPopupPreOccupancyNick',
    'UI_AdvertisingPopup',
    'UI_AdsRoulettePopup',
    'UI_FormationDetailPopup',
    'UI_IngameNoticeFullPopup',
    'UI_EventFullPopup',
    'UI_EventDungeon',
	'UI_EventThankAnniversary_rewardPopup',
	'UI_EventThankAnniversary_showDetaillPopup',
    'UI_EventWelcomeNewbie',
    'UI_EventThankAnniversary',
    'UI_EventThankAnniversaryNoChoice',
    'UI_CapsuleBoxTodayListItem',
    'UI_CapsuleBoxTodayInfoPopup',
    'UI_CapsuleScheduleListItem',
    'UI_CapsuleBoxResultPopup',
	'UI_CapsuleBox',
	'UI_CapsuleBoxRewardList',
    'UI_CapsuleBoxSchedule',
    'UI_ContentOpenPopup',
    'UI_DragonGuidePopup',
    'UI_DragonGuideListItem',
    'UI_DragonDiaryPopup',
    'UI_BattlePassPopup',
    'UI_BattlePassInfoPopup',
    'UI_BattlePassTabButton',
    'UI_PackagePopup',
    'UI_PackageTabButton',
    'UI_TeamBonus',
    'UI_TeamBonus_Dragon',
    'UI_TeamBonus_Total',
    'UI_TeamBonus_Detail',
    'UI_TeamBonusListItem',
    'UI_DragonChanceUp',
    'UI_DragonChanceUpListItem',
    'UI_CostumeEventPopup',
    'UI_GoldDungeonScene',
    'UI_PurchasePointListItem',
    'UI_MatchReady',
    'UI_MatchReadyChallengeMode',
    'UI_MatchReadyClanWar',
    'UI_RuneGuardianDungeonScene',
    'UI_AncientTowerBestDeckListItem',
    'UI_AncientTowerBestDeckPopup',
    'UI_LinkAccountPopup',
    'UI_TestDevelopment',
    'UI_TestDevelopmentListItem',
    'UI_StartingTamer',
    'UI_FevertimeConfirmPopup',
    'UI_FevertimeUIHelper',
    'UI_ClearTicketConfirm', -- 소탕 결과 보상 화면

    -- UI : 환상 던전
    'UI_EventScene_Illusion',
    'UI_IllusionScene',
    'UI_IllusionRank',
    'UI_IllusionRankListItem',

	-- UI : 해외
	'UI_SelectServerPopup',
	'UI_SelectLanguagePopup',
    'UI_LanguagePopup',

    -- UI : 약관 동의
    'UI_TermsPopup',

	-- UI : 계정 생성
	'UI_SelectStartingDragon',
	'UI_SelectStartingDragon_Detail',
	'UI_SelectNickname',

    -- UI : 대화 스크립트 재생기
    'UI_ScenarioPlayer',
    'UI_ScenarioPlayer_util', -- partial class 는 소문자로 적으면 어떨까
    'UI_ScenarioPlayer_Character',
    'UI_ScenarioPlayer_Talk',
    'UI_ScenarioPlayer_Narrate',
    'UI_ScenarioReplay',
    'UI_ScenarioReplayListItem',

	-- UI : 상점 관련
    'UI_PaymentShop',
	'UI_Shop',
    'UI_ShopTab',
    'UI_Product',
    'UI_ProductSmall',
	'UI_Package',
    'UI_Package_Bundle',
    
    'UI_ShopPackageScene',
    'UI_PackageCategoryButton',
    'UI_DragonPackageCategoryButton',

    'UI_Package_LevelUp',
    'UI_Package_LevelUp_02',
    'UI_Package_LevelUp_03',
    'UI_Package_LevelUpListItem',
    'UI_Package_AdventureBreakthrough',
    'UI_Package_AdventureClear',
    'UI_Package_AdventureClearListItem',
    -- 'UI_Package_ClanRaid_Earth',
    -- 'UI_Package_ClanRaid_Water',
    -- 'UI_Package_ClanRaid_Fire',
    -- 'UI_Package_ClanRaid_Light',
    -- 'UI_Package_ClanRaid_Dark',
    'UI_Package_Step',
    'UI_Package_Step02',
    'UI_Package_Select_Radio',
    'UI_Package_SpotSale',
    'UI_Package_New_DragonBg',
    'UI_Package_New_Dragon',
    'UI_Package_Bundle_Dependency',
    'UI_SubscriptionDayListItem',
    'UI_SubscriptionDayListItemNew',
    'UI_ShopBasic',
    'UI_PackageRandomBoxInfo',
    'UI_RandomShop',
    'UI_RandomShopListItem',
	'UI_Shop_Popup_Reinforce',
    'UI_Shop_Popup_SkillSlime',
    'UI_PromoteAutoPick',
    'UI_PromoteQuestDouble',
    'UI_SummonDrawInfo',
    'UI_GetDragonPackage',
    'UI_GetDragonPackage_LobbyButton',

    -- @ksjang 돌림판
    'UI_EventRouletteItem',
    'UI_EventRouletteInfoPopup',
    'UI_EventRouletteRewardPopup',
    'UI_EventRouletteRewardItem',
    'UI_EventRouletteAutoSetting',
    'UI_EventRouletteAutoSettingCheck',

    -- UI : 배틀패스 상점 관련
    'UI_BattlePass_Indiv',
    'UI_BattlePass_IndivCell',

    
    
    -- UI : 시련
    'UI_DmgateScene',
    'UI_DmgateStageItem',
    'UI_DmgateDifficultyItem',
    'UI_DmgateShop',
    'UI_DmgatePopup',

    -- UI : 레이드
    'UI_LeagueRaidScene',
    'UI_LeagueRaidRankItem',
    'UI_GameResult_LeagueRaid',
    'UI_LeagueRaidSeasonRewardPopup',
    'UI_ResultLeagueRaidScore',
    'UI_LeagueRaidDamageInfo',
    'UI_LeagueRaidStatisticsPopup',
    'UI_LeagueRaidOpenPopup',
    'GameWorldLeagueRaid',

    -- UI : 스토리 던전
    'UI_DragonStoryDungeonEventScene',
    'UI_StoryDungeonEventShop',
    'UI_GachaResult_StoryDungeonDragon10',

	-- UI : 모험
    'UI_AdventureSceneNew',
    'UI_AdventureStageButton',
    'UI_AdventureFirstRewardPopup',
    'UI_AdventureFirstRewardButton',
    'UI_AdventureStageInfo',
	'UI_AdventureStageInfo_IllusionDungeon',
    'UI_AdventureStageMissionInfo',
    'UI_ChapterSelect',
    'UI_ChapterSelectListItem',

    'UI_ClearTicket',
    'UI_ClearTicketDungeons',
    'UI_ClearTicketStoryDungeon',

	-- UI : 모험 준비
    'UI_ReadySceneNew',
    'UI_ReadySceneNew_Deck',
    'UI_ReadySceneNew_Deck_Illusion',
    'UI_ReadySceneNew_Deck_Raid',
    'UI_ReadySceneNew_Select',
    'UI_ReadyScene_LeaderPopup',
	'UI_ReadySceneNew_IllusionDungeon',
    'UI_LeagueRaidDeckSettings',
	
	-- UI : 전투 통계
	'UI_StatisticsPopup',
	'UI_StatisticsListItem',

    -- UI : 로비 도움말
    'UI_LobbyGuideAdventure',
    'UI_LobbyGuideWeeklyShop',
    'UI_LobbyGuideColosseum',
    'UI_LobbyGuideAncientTower',
    'UI_LobbyGuideAttrTower',
    'UI_LobbyGuideArena',

	-- UI : 콜로세움
    'UI_Colosseum',
    'UI_ColosseumResult',
    'UI_ColosseumRankInfoPopup',
    'UI_ColosseumBuffInfoPopup',
    'UI_ColosseumRewardInfoPopup',
    'UI_ColosseumRankRewardItem',
    'UI_ColosseumMatchRewardItem',
    'UI_ColosseumClanRankRewardItem',
    'UI_ColosseumAttackListItem',
    'UI_ColosseumReady',
    'UI_ColosseumReadyForDev',
    'UI_ColosseumTabRank',
    'UI_ColosseumRankListItem',
    'UI_ColosseumClanRankListItem',
    'UI_ColosseumRankingRewardPopup',
    'UI_ColosseumHistoryListItem',
    'UI_ColosseumDeckSettings',
    'UI_2DDeck',

    -- UI : 콜로세움 (ARENA)
    'UI_Arena',
    'UI_ArenaNew',
    'UI_ArenaNewStaminaChargePopup',
    'UI_ArenaNewHelp',
    'UI_ArenaNewDailyReward',
    'UI_ArenaNewTierRewardPopup',
    'UI_ArenaNewAutoPlayPopup',
    'UI_ArenaNewRivalListItem',
    'UI_ArenaNewStepRewardPopup',
    'UI_ArenaNewRivalListResetPopup',
    'UI_ArenaTabHistory',
    'UI_ArenaNewHistory',
    'UI_ArenaNewHistoryListItem',
    'UI_ArenaNewTierInfoListItem',
    'UI_ArenaTabRank',
    'UI_ArenaDeckSettings',
    'UI_ArenaNewDeckSettings',
    'UI_ArenaNewDefenceDeckSettings',
    'UI_ArenaRankListItem',
    'UI_ArenaClanRankListItem',
    'UI_ArenaResult',
    'UI_ArenaNewResult',
    'UI_ArenaHistoryListItem',
    'UI_ArenaRewardInfoPopup',
    'UI_ArenaRankInfoPopup',
    'UI_ArenaNewRankInfoPopup',
    'UI_ArenaRankingRewardPopup',
    'UI_ArenaNewRankingRewardPopup',
    'UI_ArenaReady',
    'UI_ArenaRankingListItem',
    'UI_ArenaNewRankingListItem',
    'UI_ArenaNewRankListItem',
    'UI_ArenaRankingRewardListItem',
    'UI_ArenaNewRankingRewardListItem',
    'UI_ArenaClanRankRewardListItem',
	'UI_ArenaRankClanPopup',
    'UI_ArenaRankPopup',
    'UI_ArenaNewRankPopup',
    'UI_EventArenaResult',

    -- UI : 친선전
    'UI_FriendMatchReady',
    'UI_FriendMatchReadyArena',
    'UI_FriendMatchResult',
    'UI_FriendMatchResultArena',
    'UI_FriendMatchDeckSettings',
    'UI_FriendMatchDeckSettingsArena',

	-- UI : 고대의 탑
    'UI_AncientTower',
    'UI_AncientTowerFloorInfo',
    'UI_AncientTowerRank',
    'UI_AncientTowerRankNew',
    'UI_AncientTowerListItem',
    'UI_AncientTowerRankListItem',
    'UI_AncientTowerRankListItemNew',
    'UI_AncientTowerRewardListItem',
    'UI_AncientTowerRankingRewardPopup',
    'UI_AncientTowerClanRankListItem',
    'UI_AncientTowerClanRewardListItem',
    'UI_TowerStaminaChargePopup',

    -- UI : 시험의 탑
    'UI_AttrTower',
    'UI_AttrTowerFloorInfo',
    'UI_AttrTowerListItem',
    'UI_AttrTowerMenuItem',
    'UI_AttrTowerMenuScene',
    'UI_AttrTowerRank',
    
	-- UI : 인게임
	'UI_Game',
    'UI_Game_Mana',
    'UI_GameColosseum',
    'UI_GameArena',
    'UI_GameArenaNew',
    'UI_GameEventArena',
    'UI_GameClanRaid',
    'UI_GameEventGold',
    'UI_GameResultNew',
    'UI_GameResult_Adventure',
    'UI_GameResult_AncientTower',
    'UI_GameResult_NestDungeon',
    'UI_GameResult_SecretDungeon',
    'UI_GameResult_AncientRuin',
    'UI_GameResult_RuneGuardianDungeon',
    'UI_GameResult_Illusion',
    'UI_GameResult_ClanWar',
    'UI_GameResult_Dmgate',
    'UI_GameResult_StoryDungeon',
    'UI_GamePause',
    'UI_GamePause_AncientTower',
    'UI_GamePause_NestDungeon',
    'UI_GamePause_SecretDungeon',
    'UI_GamePause_Colosseum',
    'UI_GamePause_Arena',
    'UI_GamePause_ClanRaid',
    'UI_GamePause_EventGoldDungeon',
	'UI_GameDPSPopup',
	'UI_GameDPSListItem',
    'UI_GameDebug',
    'UI_GameDebug_InfoPopup',
	'UI_GameDebug_RealTime',
    'UI_GameIllusion',
    'UI_IngameDragonPanel',
    'UI_IngameDragonPanelItem',
    'UI_IngameTamerPanelItem',
    'UI_IngameUnitInfo',
    'UI_IngameDragonInfo',
    'UI_IngameBossInfo',
    'UI_IngameBossHp',
    'UI_AutoPlaySettingPopup',
    'UI_EventGoldDungeonResult',
    'UI_ResultLeaderBoardListItem',
    'UI_ResultLeaderBoard',
    

    -- UI : 챌린지 모드
    'UI_ChallengeMode',
    'UI_ChallengeModeDeckSettings',
    'UI_LoadingChallengeMode',
    'UI_GameChallengeMode',
    'UI_ChallengeModeResult',
    'UI_ChallengeModeListItem',
    'UI_ChallengeModeRankingPopup',
    'UI_ChallengeModeRankingListItem',
    'UI_ChallengeModeInfoPopup',
    'UI_ChallengeModeRewardListItem',
    'UI_ChallengeModeRankingRewardPopup',
    'UI_ChallengeModePromotePopup',

    -- UI : 그랜드 콜로세움
    'UI_GrandArena',
    'UI_GrandArenaDeckSettings',
    'UI_GrandArenaHistoryListItem',
    'UI_UserDeckInfo_GrandArena_Popup',
    'UI_GrandArenaMatchList',
    'UI_GrandArenaMatchListItem',
    'UI_GrandArenaRankingListItem',
    'UI_GrandArenaSceneRankingListItem',
    'UI_GrandArenaRankingRewardListItem',
    'UI_GrandArenaRankingPopup',
    'UI_GrandArenaRankingRewardPopup',
    'UI_LoadingGrandArena',

	-- UI : 가방
    'UI_Inventory',
    'UI_InventorySelectSellItems',
    'UI_InventoryTab',
    'UI_InventoryTabRune',
    'UI_InventoryTabFruit',
    'UI_InventoryTabEvolutionStone',
    'UI_InventoryTabTransform',
    'UI_InventoryTabEgg',
    'UI_InventorySellItems',
    'UI_InventoryBtn',
    'UI_RuneBulkSalePopup',
    'UI_EvolutionStoneCombine',
    'UI_EvolutionStoneCombineListItem',
    'UI_RuneSetFilter',
    'UI_RuneOptionFilter',

	-- UI : 각종 랭킹
    'UI_RecommendedDragonInfoPopup',
	'UI_RecommendedDragonInfoListItem_Dungeon',
	'UI_RecommendedDragonInfoListItem_Dragon',
	'UI_RecommendedDragonInfoListItem_Party',
	'UI_OverallRankingPopup',
	'UI_OverallRankingListItem',
    
    'UI_EventRankingRewardPopup',

    -- 드래곤 픽율 공통 UI
    'UI_DragonPickRates',

    -- UI : 도감 관련
	'UI_Book',
	'UI_BookDetailPopup',
    'UI_BookEgg',
    'UI_BookEggListItem',
    'UI_BookDragonCard_Bundle',

    -- UI : 친구 시스템 관련
    'UI_FriendPopup',
    'UI_FriendPopupTab',
    'UI_FriendPopupTabFriends',
    'UI_FriendPopupTabRecommend',
    'UI_FriendPopupTabRequest',
    'UI_FriendPopupTabResponse',
    'UI_FriendListItem',
    'UI_FriendRecommendUserListItem',
    'UI_FriendRequestListItem',
    'UI_FriendResponseListItem',

    -- UI : 드래곤 관리 관련
    'UI_DragonManage_Base',
    'UI_DragonManageInfo',
    'UI_DragonLevelUp',
    'UI_DragonLevelUpHelper',
    'UI_DragonLevelUpNew', -- 2020-11-10 드래곤 레벨업 시스템 업데이트로 인한 추가
    'UI_DragonMasteryNew', -- 특성
    'UI_DragonMasteryBoardNew', -- 특성 보드
    'UI_DragonMasterySkillLevelUpPopup',
    'UI_DragonMasteryResetPopup',
    'UI_DragonMasteryLevelUp_Result',
    'UI_DragonMasteryRecoverPopup',
    'UI_DragonUpgrade',
    'UI_DragonUpgradeCombineMaterial',
    'UI_DragonUpgradeCombineMaterialItem',
    'UI_DragonUpgradeCombineMaterialConfirmPopup',
	'UI_DragonSkillEnhance',
    'UI_DragonEvolution',
    'UI_SkillDetailPopup',
    'UI_HelpStatus',
    'UI_DragonRunes',
    'UI_DragonRunesGrind',
    'UI_DragonRunesGrindSetting',
    'UI_DragonRunesGrindFirstPopup',
    'UI_DragonRunesEnhance',
    'UI_DragonRunesBulkEquip',
    'UI_DragonRunesBulkEquipRuneTab',
    'UI_DragonRunesBulkEquipDragonTab',    
    'UI_DragonRunesBulkEquipItem',
    'UI_DragonRunesBulkEquipPopup',
    'UI_DragonRunesEquipPopup',
    'UI_DragonFriendship', 
	'UI_DragonReinforcement',
	'UI_DragonReinforceItem',
    'UI_DragonSkillMove',
    'UI_DragonSkillInfo',
    'UI_DragonSelectPopup',
    'UI_DragonTransformChange',
    'UI_DragonSkinManageInfo',
    'UI_DragonSkinListItem',

	-- UI : 드래곤 관리 - 결과
    'UI_DragonManageFriendshipResult',
    'UI_DragonChangeResult',
    'UI_DragonEvolutionResult',
    'UI_DragonUpgradeResult',
    'UI_DragonLevelupResult',
	'UI_DragonSkillEnhance_Result',
	'UI_DragonReinforceResult',
    'UI_DragonTransformChangeResult',
    
	-- UI : 드래곤 평가
	'UI_DragonBoardPopup',
	'UI_DragonBoardListItem',
	'UI_DragonBoardPopup_Evaluate',
	'UI_DragonBoardPopup_Write',

	-- UI : 테이머 관리
	'UI_TamerManagePopup',
    'UI_TamerManagePopup_Colosseum',
    'UI_TamerListItem',
    'UI_TamerCostumeListItem',
    'UI_TamerCostumeConfirmPopup',
	'UI_SkillDetailPopup_Tamer',
    'UI_SkillDetailPopupListItem_Tamer',
	'UI_SkillEnhance',

	-- UI: 유저 상세 정보
	'UI_UserInfoDetailPopup',
	'UI_UserInfoDetailPopup_SetLeader',
    'UI_UserInfoDetailPopup_SetTitle',

    -- UI : 탐험(exploration)
    'UI_Exploration',
    'UI_ExplorationIng',
    'UI_ExplorationLocationButton',
    'UI_ExplorationReady',
    'UI_ExplorationResultPopup',

    -- UI : EVENT
    'UI_EventPopup',
    'UI_EventPopupTabButton',
    'UI_EventPopupTab_Attendance',
    'UI_EventPopupTab_EventAttendance',
    'UI_EventPopupTab_EventAttendance1st',
    'UI_EventPopupTab_AccessTime',
    'UI_EventPopupTab_Banner',
    'UI_EventPopupTab_Shop',
    'UI_EventPopupTab_Package',
    'UI_EventPopupTab_Notice',
    'UI_EventPopupTab_HBShop',
    'UI_EventPopupTab_HBShop_Coupon',
    'UI_EventPopupTab_PackageGrowth',
    'UI_EventPopupTab_Scroll',
    'UI_PurchasePointBg',
    'UI_PurchasePointBgNew',
    'UI_PurchasePointRewardSelectPopup',
    'UI_EventPopupTab_PurchasePoint',
    'UI_EventPopupTab_PurchasePointNew',
    'UI_EventPopupTab_PurchaseDaily',
    'UI_ExchangeProductListItem',
    'UI_AccessTimeDataListItem',
    'UI_ExchangeEvent',
    'UI_ExchangeEventListItem',
    'UI_DiceEvent',
	'UI_DailyMisson_Clan',
    'UI_EventGoldDungeon',
    'UI_EventGoldDungeonListItem',
    'UI_EventGoldDungeonPopup',
    'UI_EventMatchCard',
    'UI_EventMatchCardPlay',
    'UI_EventMatchCardListItem',
    'UI_EventMatchCardTimeListItem',
    'UI_EventMatchCardResult',
    'UI_EventMandragoraQuest',
    'UI_EventMandragoraQuestListItem',
	'UI_Event1stComeback',
    'UI_EventAlphabet', -- 알파벳 이벤트
    'UI_EventAlphabetListItem',
    'UI_EventAlphabetInfoPopup',
    'UI_EventAlphabetConfirmPopup',
    'UI_EventAdvent',
    'UI_EventBingoPackagePopup',
    'UI_EventBingoRewardListItem',
    'UI_EventBingoListItem',
    'UI_EventBingo',   -- 빙고 이벤트
	'UI_EventRoulette', -- 룰렛 이벤트
	'UI_EventRouletteRankingPopup',
    'UI_EventRouletteRankingListItem',
    'UI_EventRouletteRankingTab',
    'UI_IllusionShop',-- 환상 던전 교환소
    'UI_IllusionRewardPopup', -- 환상 던전 보상 팝업
	'UI_ItemPickPopup',
    'UI_CrossPromotion',
    'UI_CustomEnhance',
    'UI_CustomEnhanceFruit',
    'UI_EventVIP', -- @yjkil 2022.01.13 VIP 설문조사
    'UI_HighbrowVipPopup', -- @yjkil 2022.02.14 VIP 

    -- 신화 드래곤 투표 이벤트
    'UI_EventPopupTab_EventVote', -- 인트로 
    'UI_EventVoteChoice', -- 투표
    'UI_EventVoteChoiceConfirmPopup', -- 투표 확인 팝업
    'UI_EventVoteRewardPopup', --투표 보상 팝업
    'UI_EventVoteRanking',
    'UI_EventVoteRankingItem',
    'UI_EventVoteDragonCard',
    'UI_EventVoteRankingResult', -- 투표 월드 랭킹 결과

    -- 신화 드래곤 인기 가챠
    'UI_EventPopupTab_DragonPopularityGacha',

	-- UI : 출석 이벤트
    'UI_AttendanceBasicListItem',
    'UI_AttendanceSpecialListItem',
    'UI_AttendanceSpecialListItem_1st',

	-- UI : 연출
	'DirectingCharacter',
    'UI_DragonCard_Gacha',
    'UI_DragonCard_StoryDungeonGacha',

	-- UI : 채팅
	'UI_ChatPopup',
    'UI_ChatPopup_WhisperTab',
    'UI_ChatPopup_ClanTab',
    'UI_ChatList',
    'UI_ChatListItem',
    'UI_ChatListItem_msg',
    'UI_ChatListItem_myMsg',
    'UI_ChatListItem_systemMsg',
    'UI_ChatListItem_broadcast', -- 소원 구슬 이벤트용 (커스텀해서 다른데서 돌려써도 됨)
    'UI_ChatIgnoreListItem',
    'UI_ChatMacroListItem',

	-- UI : 설정
	'UI_Setting',
    'UI_SettingAccountTab',
    'UI_SettingDevTab',
    'UI_SettingGameTab',
    'UI_SettingInfoTab',
    'UI_SettingTestCode',
    'UI_CommunityPopup',
    'UI_DragonDevApiPopup',
    'UI_RuneDevApiPopup',
    'UI_InvenDevApiPopup',
    'UI_EggSimulator',
    'UI_TranslationViewer',

    'UI_HbrwLoungePopup',

    -- UI : 클랜
    'UI_Clan',
    'UI_ClanMemberListItem',
    'UI_ClanTabInfo',
    'UI_ClanTabMember',
    'UI_ClanTabRank',
    'UI_ClanGuest',
    'UI_ClanListItem',
    'UI_ClanGuestTabJoin',
    'UI_ClanGuestTabFound',
    'UI_ClanGuestTabRequest',
    'UI_ClanGuestTabRank',
    'UI_ClanSetting',
    'UI_ClanMark',
    'UI_ClanMarkListItem',
    'UI_ClanInfoDetailPopup',
    'UI_ClanAttendanceReward',
    'UI_ClanAttendanceRewardInfo',
    'UI_ClanAcceptPopup', -- 가입 승인 관리 팝업 (마스터, 부마스터 권한)
    'UI_ClanAcceptListItem',
    'UI_ClanRaid',
    'UI_ClanRaidRankListItem',
    'UI_ClanRaidResult',
    'UI_ClanRaidRankPopup',
    'UI_ClanRaidRankingPopup',
    'UI_ClanRaidLastRankingTab',
    'UI_ClanRaidRankingRewardPopup',
    'UI_ClanRaidTrainingPopup',
    'UI_ClanRaidTabRank',
    'UI_ClanRaidTabContribution',
    'UI_ClanBoardListItem',
    'UI_ClanBoardPopup_Write',

    -- UI : 클랜전
    'UI_ClanWar_GroupStage',
    'UI_ClanWar_GroupPaging',
    'UI_ClanWarDeckSettings',
    'UI_ClanWarLeagueRankInfoPopup',
	'UI_ClanWarLeagueResultPopup',
	'UI_ClanWarRewardPopup',
    'UI_ClanwarRewardInfoPopup',
    'UI_ClanWarLastGroupStagePopup',
	'UI_ClanWarTournamentTreeFinalItem',
	'UI_ClanWarTournamentTreeLeaf',
    'UI_ClanWarTournamentTree',
	'UI_ClanWarAllRankListItem',
    'UI_ClanWarMatchInfoDetailPopup',
    'UI_ClanWarMatchingSceneListItem',
    'UI_ClanWarMatchingScene',
    'UI_ClanWarSelect_RivalListItem',
    'UI_ClanWarSelectSceneListItem',
    'UI_ClanWarSelectSceneDefendHistoryItem',
    'UI_ClanWarSelectScene',
	'UI_LoadingClanWar',

    -- UI 둥지
    'UI_DragonLair', -- 메인
    'UI_DragonLairRegister', -- 등록 
    'UI_DragonLairRegisterConfirm', -- 등록 확인
    'UI_DragonLairRegisterResult', -- 등록 결과
    'UI_DragonLairBlessingPopup', -- 축복 팝업
    'UI_DragonLairBlessingPopupItem', -- 축복 팝업 아이템
    'UI_DragonLairBlessingAutoPopup', -- 자동 축복 팝업    
    'UI_SimplePricePopup',

    -- Forest
    'SceneForest',
    'UI_Forest',
    'UI_Forest_ChangePopup',
    'UI_Forest_StuffLevelupPopup',
    'UI_Forest_StuffListPopup',
    'UI_Forest_StuffListItem',
    'UI_Forest_ExtensionBoard',
    'ServerData_Forest',
    'TableForestStuffType',
    'TableForestStuffLevelInfo',
    'StructForestEvent',
    'StructUserInfoForest',
    'ForestTerritory',
    'ForestObject',
    'ForestCharacter',
    'ForestTamer',
    'ForestDragon',
    'ForestShadow',
    'ForestStuff',
    'ForestUserStatusUI',
    'ForestStuffUI',

    -- 덱 프리셋
    'UI_PresetDeckList',
    'UI_PresetDeckListItem',
    'UI_PresetDeckSetting',
    'UI_PresetDeckSetting_Select',
    'UI_PresetDeckSetting_Deck',

    -- 룬 프리셋
    'UI_RunePreset',
    'UI_RunePresetItem',
    'UI_RunePresetBulkSettingPopup',
    'UI_DragonRunesBulkEquipPresetTab',

    -- Tutorial
    'UI_TutorialPlayer',
    'TutorialManager',
    'TutorialHelper',

    -- Network
    'Network',
    'socket',

    -- UI : Generated

    -- 명예의 전당
    'UI_HallOfFameHelp',
	'UI_HallOfFameListItem',
    'UI_HallOfFame',
	'UI_HallOfFameRankListItem',
    'UI_HallOfFameRank',

    -- 개인 패스
    'UI_IndivPassScene',
}

-------------------------------------
-- function loadModule
-------------------------------------
function loadModule()
	-- penlight lua 라이브러리
    pl = require 'pl.import_into'()
    csv = require 'perpleLib/lua_csv'

    for i,v in ipairs(t_module) do
        require(v)
    end
end

local t_except_reload = {
    ['SoundMgr'] = true,
    ['uilib/UIManager'] = true,
    ['uilib/UILoader'] = true,
    ['uilib/TableView'] = true,
    ['socket'] = true,
}
-------------------------------------
-- function reloadModule
-------------------------------------
function reloadModule()
    print('#############################')
    print('## reloadModule() start    ##')

    -- 서버에서 받아서 저장 중인 테이블 백업
    -- local t_backup_server_table = TABLE:backupServerTable()
    for i,v in ipairs(t_reload_modules) do
        -- if not (t_except_reload[v]) then
            package.loaded[v] = nil
            require(v)
        -- end
    end

    -- TABLE:init()    
	-- g_constant:readDataFile()

    -- -- 서버에서 받아서 저장 중인 테이블 적용
    -- for i,v in pairs(t_backup_server_table) do
    --     TABLE[i] = v
    -- end
    print('## reloadModule() end      ##')
    print('#############################')
end

-------------------------------------
-- function loadModuleForPatchScene
-- @brief patch 시점에서 필요한 lua module을 별도로 지정
-- @comment 면밀한 관리 필요!
-------------------------------------
function loadModuleForPatchScene()
	local l_module_for_patch = {
		'Cocos2d',
		'Cocos2dConstants',
		'lib/net',
		--'lib/class',
		--'lib/utils',
		--'lib/Translate',
		'lib/scheduler',
		'lib/SocketTCP',
		'lib/math',
		'lib/Radian',
		'uilib/UIManager',
		'uilib/UI',
		'uilib/UILoader',
		'uilib/TableView',
        'uilib/Notification',
		'perpleLib/StringUtils',
		'perpleLib/sn',
		'perpleLib/crand',
		'perpleLib/PerpleScene',
		'LuaBridge',
		--'Global',
		'SoundMgr',
		'SoundMgrController',
		'SoundMgrProtected',
		'PatchData',
		'PatchCore',
		--'PatchChecker',
		'ApkExpansion',
		'Coroutine',
		'LocalPushMgr',
		'Analytics',
		'NaverCafeManager',
		'ScriptCache',
		--'CppFunctions',
		'XorCipher',
		'PackageManager',
		'FullPopupManager',

		-- CONSTANT 
		'Constant',
		'ConstantUrl',

		-- ServerData
		'ServerData_Adventure',

		-- Util
		'SDKManager',
		--'ErrorTracker',
        'ServerTime',
		'TimeLib',
		'Table',
		'TableClass',
		'SecurityNumber',
		'ResPreloadMgr',
		--'LocalData',
		'NumberLoop',
		'Stopwatch',
		'IconHelper',
		'ResHelper',
		'AnimatorHelper',
		'UIHelper',
		'BroadcastMgr',

		-- Table
		'TableDragon',
		'TableLoadingGuide',
        'TableLanguageConfig',

		-- Scene
		--'SceneLogo',
		--'ScenePatch',

		-- Animator
		'Animator',
		'AnimatorPng',
		'AnimatorSpine',
		'AnimatorVrp',
		'SpineCacheManager',

		-- UIC (UI Component)
		'UIC_Node',
		'UIC_Button',
		'UIC_LabelTTF',
		'UIC_RichLabel',
		'UIC_RichLabelCore',
		'UIC_RadioButton',

		-- UI : 분류 없음
		'UI_BlockPopup',
		'UI_Network',
		'UI_NetworkLoading',
		'UI_TitleScene',
		'UI_TitleSceneLoading',
		'UI_LoadingGuide',
		'UI_LoadingGuide_Patch',
        'UI_LoadingArena',
		'UI_Popup',
		'UI_SimplePopup',
		'UI_SimplePopup2',
        

		-- UI : 햬외
		'UI_SelectServerPopup',
		'UI_SelectLanguagePopup',
        'UI_LanguagePopup',
        

		-- Network
		'Network',
		'socket',
	}

	--pl = require 'pl.import_into'()
	csv = require 'perpleLib/lua_csv'
	for i,v in ipairs(l_module_for_patch) do
        require(v)
    end
end