local t_module = {
    'Cocos2d',
    'Cocos2dConstants',
    'lib/net',
    'lib/class',
    'lib/utils',
    'lib/Translate',
    'lib/scheduler',
    'lib/SocketTCP',
    'lib/math',
    'lib/Radian',
    'uilib/UIManager',
    'uilib/UI',
    'uilib/UILoader',
    'uilib/TableView',
    'uilib/Notification',
    'uilib/NotificationBroadcast',
    'perpleLib/StringUtils',
    'perpleLib/sn',
    'perpleLib/crand',
    'perpleLib/PerpleScene',
    'LuaBridge',
    'SoundMgr',
    'SoundMgrController',
    'SoundMgrProtected',
    'PatchData',
    'PatchCore',
    'PatchChecker',
    'ApkExpansion',
    'Coroutine',
	'LocalPushMgr',
    'Analytics',
    'AdsManager',
    'ScriptCache',
    'CppFunctions',
    'XorCipher',

	-- CONSTANT 
    'Constant',
    'ConstantUrl',
	'ConstantGameMode',
    'ConstantDragonEvolution',
    'ConstantDragonGrade',
    'ConstantAttribute',
    'ConstantString',
    'ConstantStatusEffect',
    'ConstantColosseum',
    'ConstantColor',
    'Global',

    -- Struct
    'Structure',
    'StructEventPopupTab',
    'StructAdventureChapterAchieveInfo',
    'StructAdventureStageInfo',
    'StructCalendarDay',
    'StructAttendanceData',
    'StructExchangeProductData',
    'StructRuneObject',
    'StructRuneSetObject',
    'StructDragonObject',
    'StructSlimeObject',
    'StructFriendshipObject',
	'StructStatusEffect',
    'StructIndividualStatus',
    'StructFreeDragonSummonInfo',
    'StructQuestData',
    'StructUserInfo',
    'StructUserInfoFriend',
    'StructUserInfoColosseum',
    'StructUserInfoAncientTower',
    'StructWaveRegenGroup',
    'StructCollisionData',
	'StructBookData',
    'StructAncientTowerFloorData',
    'StructProduct',
    'StructProductSubscription',
    'StructMail',
    'StructSubscribedInfo',
    'StructHighbrowProduct',

	-- ServerData
    'ServerData',
    'ServerData_User',
	'ServerData_Tamer',
    'ServerData_Dragons',
    'ServerData_Slimes',
    'ServerData_Deck',
    'ServerData_Staminas',
    'ServerData_Adventure',
    'ServerData_AdventureFirstReward',
    'ServerData_NestDungeon',
    'ServerData_SecretDungeon',
    'ServerData_AncientTower',
    'ServerData_Stage',
    'ServerData_AutoPlaySetting',
    'ServerData_Runes',
	'ServerData_Quest',
    'ServerData_Inventory',
    'ServerData_Friend',
	'ServerData_Shop',
    'ServerData_Subscription',
    'ServerData_Mail',
    'ServerData_Item',
    'ServerData_Attendance',
    'ServerData_Exchange',
    'ServerData_Exploration',
    'ServerData_HotTime',
    'ServerData_Event',
    'ServerData_Highlight',
	'ServerData_Ranking',
	'ServerData_Formation',
	'ServerData_DragonBoard',
    'ServerData_Eggs',
    'ServerData_Hatchery',
    'ServerData_StartTamer',
	'ServerData_Book',
    'ServerData_Colosseum',
    'ServerData_AccessTime',
    'ServerData_MasterRoad',
    'ServerData_ContentLock',
    'ServerData_AutoItemPick',
    'ServerData_Tutorial',
    'ServerData_Highbrow',
    'ServerData_Advertising',
    'ServerData_EvolutionStone',

    -- Interface
    'IEventDispatcher',
	'IEventListener',
    'IHighlight',
    'IStateHelper',
    'ICharacterStatusEffect',
    'ITopUserInfo_EventListener',
    'ITabUI',
	'ISkillMultiAttack',
    'ISkillSound',

    -- Util
    'SDKManager',
	'ErrorTracker',
    'Action',
    'TimeLib',
    'Table',
    'TableClass',
    'SecurityNumber',
    'ResPreloadHelper',
    'ResPreloadMgr',
    'NumberLabel',
	'NumberLabel_Pumping',
    'FpsMeter',
    'LevelupDirector',
    'LevelupDirector_GameResult',
    'MapManager',
    'LocalData',
    'ChatIgnoreList',
    'ScenarioViewingHistory',
	'ConstantData',
    'CollisionHelper',
    'DropHelper',
    'DragonAutoSetHelper',
    'DragonSkillBonusHelper',
    'DragonSkillManager',
    'DragonSkillIndivisualInfo',
    'DragonSkillCore',
    'SumRandom',
	'NumberLoop',
    'ValidationAssistant',
    'Counter',
    'Stopwatch',
    'Camera',
    'CameraTouchHandler',
    'CameraTouchHandler_Lobby',
    'SwipeGesture',
    'ValidationDragon',
    'EquationHelper',
	'SkillHelper',
	'SkillTargetFinder',
    'StatusEffectHelper',
    'AreaOfEffectHelper',
    'ShaderCache',
    'SortManager',
    'SortManager_Rune',
    'SortManager_Fruit',
    'SortManager_EvolutionStone',
    'SortManager_Dragon',
    'SortManager_Friend',
    'SimplePrimitivesDraw',
	'StageMissionMgr',
	'LogRecorder',
	'LogRecorderWorld',
	'LogRecorderChar',
    'UINavigatorDefinition',
    'UINavigator',
    'RenderTextureBatchNode',
    'AncientTowerScoreCalc',
	
    'RuneEnchantHelper',
	'IconHelper',
    'ResHelper',
    'AnimatorHelper',
	'SensitivityHelper',
	'MailHelper',
	'BattleStatisticsHelper',
	'UIHelper',
    'QuickLinkHelper',
    'GoogleHelper',

    'ChatClientSocket',
    'ChatManager',
    'ChatContent',
    'ChatContentList',
    'BroadcastMgr',

    -- Table
    'TableStageDesc',
    'TableDragon',
    'TableDragonType',
    'TableDragonExp',
    'TableDragonSkill',
	'TableDragonSkillModify',
    'TableMonster',
    'TableMonsterHitPos',
	'TableMonsterSkill',
    'TableEnemyMove',
    'TableFriendship',
    'TableFriendshipVariables',
    'TableFriendBuff',
    'TableFruit',
    'TableUserLevel',
    'TableReqGold',
    'TableDrop',
    'TableTamer',
	'TableTamerSkill',
    'TableTamerTitle',
    'TableGradeInfo',
    'TableEvolutionInfo',
    'TableStatus',
    'TableFormation',
    'TableRuneSet',
    'TableRuneGrade',
    'TableRuneMoptStatus',
    'TableItem',
    'TableItemRand',
	'TableQuest',
	'TableMasterRoad',
    'TableSecretDungeon',
    'TableStageMission',
    'TableCalendar',
    'TableOption',
    'TableStaminaInfo',
    'TableScenarioResource',
    'TableDragonPhrase',
    'TableSlime',
    'TableSlimeExp',
	'TableLoadingGuide',
    'TableExchange',
    'TableDragonCombine',
    'TableStatusEffect',
    'TableExplorationList',
    'TableColosseumBuff',
    'TableStageData',
    'TableHelp',
    'TableGoogleQuest',
    'TableSummonGacha',
    'TableUILocation',
    'TableHighbrow',
    'TableSkillSound',
    'TableEvolutionItemCombine',

    -- Scene
    'SceneCommon',
    'SceneLogo',
    'ScenePatch',
    'SceneTitle',
    'SceneLobby',
    'SceneDV',
    'SceneGame',
    'SceneGameColosseum',
    'SceneGameIntro',
    'SceneAdventure',
    'SceneNestDungeon',
    'SceneSecretDungeon',

    -- Phys
	'PhysWorld',
    'PhysObject',

	-- Animator
    'Animator',
    'AnimatorPng',
    'AnimatorSpine',
    'AnimatorVrp',

	-- Entity GameWorld
    'Entity',
    'GameWorld',
    'GameWorldColosseum',
    'GameWorldIntro',
    'GameWorld_Touch',
    'GameWorld_Formation',
    'GameWorld_Unit',
    'GameWorld_Gold',
	'GameWorld_KeyEvent',
    'GameState',
    'GameState_AncientTower',
    'GameState_NestDungeon',
    'GameState_NestDungeon_Dragon',
    'GameState_NestDungeon_Nightmare',
    'GameState_NestDungeon_Tree',
    'GameState_NestDungeon_Gold',
    'GameState_NestDungeon_Jewel',
    'GameState_SecretDungeon_Relation',
    'GameState_Colosseum',
    'GameState_Intro',
    'GameAuto',
    'GameAuto_Hero',
    'GameAuto_Enemy',
    'GameCoolTime',
    'GameMana',
    'GameDragonSkill',
    'GameCamera',
    'GameTimeScale',
    'GameHighlightMgr',
    'DropItemMgr',
    'DropItemMgr_Intro',
	'ShakeManager',
    'BenchmarkManager',
    
	-- CARRIER
	'ActivityCarrier',
	'EventCarrier',
	
    -- MAP
    'ScrollMap',
    'ScrollMapLayer',
    'AnimationMap',
    	
	-- MISSILE
	'Missile',
    'MissileBoomerang',
    'MissileCurve',
    'MissileDrop',
    'MissileDropGuid',
    'MissileDropRandom',
    'MissileDropTarget',
    'MissileDropZigzag',
    'MissileGuid',
    'MissileGuidTarget',
    'MissileTarget',
    'MissileZigzag',
    'MissileEffecter',
    'MissileLua',
    'MissileBounce',
    'MissileFix',
    'require_MissileLua',
	'MissileGuide',

	-- CHARACTER
	'Character',
    'CharacterEvent',
    'CharacterState',
    'CharacterSkill',
    'CharacterStateDelegate',
    'Dragon',
    'DragonState',
    'Monster',
    'MonsterLua_Boss',
    'Monster_GiantDragon',
    'Monster_GoldDragon',
    'Monster_Tree',
	'Monster_WorldOrderMachine',
    'Monster_DarkNix',
    'Tamer',
	'TamerSkill',
    'require_EnemyLua',
    'EnemyAppear',
    'EnemyMovementMgr',
    'MissileFactory',
    'MissileLauncher',
    
	-- COMMON MISSILE (공통탄)
	'CommonMissile',
	'CommonMissile_Straight',
	'CommonMissile_Guide',
	'CommonMissile_Cruise',
	'CommonMissile_Shotgun',
	'CommonMissile_Release',
	'CommonMissile_High',
	'CommonMissile_Bounce',
	'CommonMissile_Multi',

    -- ITEM
    'DropItem',

	-- STATUS EFFECT
	'StatusEffect',
    'StatusEffectUnit',
    'StatusEffectUnit_AddDmg',
    'StatusEffectUnit_AddDmgOneTime',
    'StatusEffectUnit_Dot',
    'StatusEffectUnit_Dot_Damage',
    'StatusEffectUnit_Dot_Heal',

    'StatusEffect_AddDmgOneTime',
	'StatusEffect_Sleep',
    'StatusEffect_Bleed',
    'StatusEffect_Poison',
    'StatusEffect_Protection',
	'StatusEffect_Silence',
	'StatusEffect_AttributeChange',
	'StatusEffect_Dispell',
    'StatusEffect_Zombie',
    'StatusEffect_Immortal',
    'StatusEffect_Modify',
    'StatusEffect_AddMana',
    'StatusEffect_ManaReduce',
    'StatusEffect_Resurrect',
    'StatusEffect_Transfer',
    'StatusEffect_ConditionalBuff',
    'StatusEffect_ConsumeToMissile',
    'StatusEffect_ConditionalModify',
    'StatusEffect_AccelMana',

    'StatusEffectEdgeDirector',
	'StatusEffectIcon',

	-- EFFECT
	'EffectLink',
    'EffectLinearDot',
    'EffectBezierLink',
	'EffectHeal',
    'EffectMotionStreak',
    
	-- SKILL HELPER
	'SkillHitEffectDirector',

    -- SKILL    
	'Skill',
    'SkillLaser',
    'SkillLaser_Darknix',
	'SkillChainLightning',
	'SkillThrowBuff',
    'SkillGuardian',
    'SkillMeleeHack',
	'SkillAoERound',
	'SkillAoERound_Sura',
    'SkillAoERound_Throw',
    'SkillAoESquare',
    'SkillAoESquare_Height',
    'SkillAoESquare_Height_Top',
	'SkillAoESquare_Width',
    'SkillAoESquare_Width_Right',
	'SkillAoESquare_Charge',
	'SkillAoESquare_Wonder',
	'SkillAoECone',
	'SkillAoECone_Crash',
	'SkillAoEWedge',
    'SkillLeafBlade',
    'SkillSummon',
    'SkillTransform',
    'SkillSpatter',
    'SkillCross',
	'SkillLeap',
	'SkillExplosion',
    'SkillSuicideExplosion',
	'SkillRolling',
	'SkillConditionalAddEffect',
	'SkillCounterAttack',
	'SkillSpiderWeb',
    'SkillHeartOfRuin',
	'SkillBurst',
	'SkillFieldCheck',
	'SkillVoltesX',
	'SkillCharge',
	'SkillRush',
    'SkillRapidShot',
	'SkillRapidShot_AddAttack',
	'SkillEnumrate',
	'SkillEnumrate_Curve',
	'SkillEnumrate_Normal',
	'SkillEnumrate_Penetration',
    'SkillBind',

    'SkillHealSingle',
    'SkillHealAround',
    'SkillHealAoERound',
    'SkillHealAoESquare_Height',
    'SkillHealAoESquare_Width',

    -- SKILL INDICATOR
    'SkillIndicatorMgr',
    'SkillIndicatorMgr_Intro',
    'SkillIndicator',
    'SkillIndicator_Laser',
    'SkillIndicator_Target',
    'SkillIndicator_LeafBlade',
	'SkillIndicator_AoERound',
	'SkillIndicator_AoESquare',
    'SkillIndicator_AoESquare_Height',
    'SkillIndicator_AoESquare_Height_Top',
    'SkillIndicator_AoESquare_Width',
    'SkillIndicator_AoESquare_Width_Right',
	'SkillIndicator_AoESquare_Multi',
	'SkillIndicator_AoECone',
	'SkillIndicator_AoEWedge',
	'SkillIndicator_X',
	'SkillIndicator_Penetration',
    'SkillIndicator_Cross',

	'WaveMgr',
    'WaveMgr_AncientTower',
    'WaveMgr_SecretRelation',
    'WaveMgr_Colosseum',
    'DynamicWave',
	
	-- 인게임 Util
    'DamageCalc',
    'FormationMgr',
    'FormationMgr_TargetRule',
    'StatusCalculator',
    'StatusCalculatorFormula',
    'TriggerHpPercent',
    'TriggerTime',

    -- UIC (UI Component)
    'UIC_Node',
    'UIC_Button',
    'UIC_CheckBox',
    'UIC_ClippingNode',
    'UIC_TableViewProtocol',
    'UIC_TableView',
    'UIC_ChatView',
    'UIC_TableViewCell',
    'UIC_TableViewTD',
    'UIC_ChatTableView',
    'UIC_ChatTableViewCell',
    'UIC_RadioButton',
    'UIC_LabelTTF',
    'UIC_RichLabel',
    'UIC_RichLabelCore',
    'UIC_TabManager',
    'UIC_SortList',
    'UIC_Factory',
    'UIC_IndivisualStats',
    'UIC_DragonAnimator',
    'UIC_DragonAnimatorDirector',
	'UIC_DragonAnimatorDirector_Summon',
    'UIC_ScrollLabel',
    'UIC_BroadcastLabel',
    'UIC_EggPicker',
    'UIC_ExtendedUI',

    -- UI : CARD
    'UI_Card',
    'UI_CharacterCard',
    'UI_RelationCard',
    'UI_ItemCard',
    'UI_RuneCard',
    'UI_MonsterCard',
	'UI_RewardCard',
    'UI_DragonSkillCard',
    'UI_MonsterSkillCard',

	-- UI : 분류 없음
    'UI_BlockPopup',
    'UI_Network',
    'UI_NetworkLoading',
    'UI_TitleScene',
    'UI_TitleSceneLoading',
	'UI_LoadingGuide',
	'UI_LoadingGuide_Patch',
    'UI_Lobby',
    'LobbyMapSpotMgr',
    'LobbyMap',
    'LobbyMapFactory',
    'LobbyWorldAdapter',
    'LobbyCharacter',
    'LobbyTamer',
    'LobbyTamerBot',
    'LobbyDragon',
    'LobbyShadow',
    'LobbyUserStatusUI',
    'LobbyManager',
    'UI_RewardListPopup',
    'UI_Popup',
    'UI_SimplePopup',
    'UI_SimplePopup2',
	'UI_ConfirmPopup',
	'UI_ObtainPopup',
	'UI_ErrorPopup',
    'UI_SimpleDragonInfoPopup',
    'UI_SimpleMonsterInfoPopup',
    'UI_Hatchery',
    'UI_HatcheryCombineTab',
    'UI_HatcheryCombinePopup',
    'UI_HatcheryCombineItem',
    'UI_HatcherySummonTab',
    'UI_HatcheryIncubateTab',
    'UI_HatcheryRelationTab',
    'UI_HatcheryRelationItem',
	'UI_ToastPopup',
    'UI_SecretFindPopup',
	'UI_Tooltip_Indicator',
    'UI_Tooltip_Skill',
    'UI_TopUserInfo',
    'UI_GoodsInfo',
    'UI_StaminaInfo',

    'UI_GachaResult_Dragon',
    'UI_DragonAppear',
    'UI_GuidePopup',
    'UI_NestDungeonScene',
    'UI_NestDungeonListItem',
    'UI_NestDungeonStageListItem',
    'UI_SecretDungeonScene',
    'UI_SecretDungeonListItem',
    'UI_SecretDungeonStageListItem',
    'UI_EditBoxPopup',
    'UI_SimpleEditBoxPopup',
    'UI_FruitFeedPress',
    'UI_UserDeckInfoPopup',
    'UI_BattleMenu',
    'UI_BattleMenuItem',
	'UI_QuestPopup',
    'UI_QuestListItem',
	'UI_MasterRoadPopup',
    'UI_MasterRoadPopup_Link',
    'UI_MailPopup',
    'UI_MailListItem',
    'UI_AcquisitionRegionInformation',
    'UI_AcquisitionRegionListItem',
    'UI_NotificationInfoElement',
    'UI_NotificationInfo',
    'UI_ItemInfoPopup',
    'UI_ChapterAchieveRewardPopup',
    'UI_NotificationFullInventoryPopup',
    'UI_DragonInfoBoard',
    'UI_MonsterInfoBoard',
	'UI_FormationPopup',
	'UI_FormationListItem',
    'UI_UserInfoMini',
    'UI_UserLevelUp',
    'UI_ContentLock',
    'UI_ChangeNickPopup',
    'UI_LoginPopup',
    'UI_WebView',
    'UI_Help',
    'UI_DragonGoodbyeResult',
    'UI_QuickPopup',
    'UI_CouponPopup',
    'UI_CouponPopup_Confirm',
    'UI_CouponPopupPreOccupancyNick',
    'UI_AdvertisingPopup',
    'UI_FormationDetailPopup',

    -- UI : 약관 동의
    'UI_TermsPopup',

    -- UI : 대화 스크립트 재생기
    'UI_ScenarioPlayer',
    'UI_ScenarioPlayer_util', -- partial class 는 소문자로 적으면 어떨까
    'UI_ScenarioPlayer_Character',
    'UI_ScenarioPlayer_Talk',
    'UI_ScenarioPlayer_Narrate',

	-- UI : 상점 관련
	'UI_Shop',
    'UI_ShopTab',
    'UI_ShopPopup',
    'UI_Product',
	'UI_Package',
    'UI_SubscriptionPopup',
    'UI_SubscriptionPopup_Ing',
    'UI_SubscriptionDayListItem',

    -- UI : 계정 생성
	'UI_StartTamerSelect',

	-- UI : 모험
    'UI_AdventureSceneNew',
    'UI_AdventureStageButton',
    'UI_AdventureFirstRewardPopup',
    'UI_AdventureFirstRewardButton',
    'UI_AdventureStageInfo',
    'UI_AdventureStageMissionInfo',
    
	-- UI : 모험 준비
	'UI_ReadyScene',
    'UI_ReadyScene_Deck',
    'UI_ReadyScene_Select',
	'UI_ReadyScene_LeaderPopup',
	
	-- UI : 전투 통계
	'UI_StatisticsPopup',
	'UI_StatisticsListItem',

	-- UI : 콜로세움
    'UI_Colosseum',
    'UI_ColosseumResult',
    'UI_ColosseumRankInfoPopup',
    'UI_ColosseumBuffInfoPopup',
    'UI_ColosseumRewardInfoPopup',
    'UI_ColosseumRankRewardItem',
    'UI_ColosseumMatchRewardItem',
    'UI_ColosseumAttackListItem',
    'UI_ColosseumReady',
    'UI_ColosseumReadyForDev',
    'UI_ColosseumRankListItem',
    'UI_ColosseumRankingRewardPopup',
    'UI_ColosseumHistoryListItem',
    'UI_ColosseumDeckSettings',
    'UI_3DDeck',

	-- UI : 고대의 탑
    'UI_AncientTower',
    'UI_AncientTowerFloorInfo',
    'UI_AncientTowerRank',
    'UI_AncientTowerListItem',
    'UI_AncientTowerRankListItem',
    'UI_AncientTowerRewardListItem',
    'UI_AncientTowerRankingRewardPopup',

	-- UI : 인게임
	'UI_Game',
    'UI_Game_Mana',
    'UI_GameColosseum',
    'UI_GameResultNew',
    'UI_GameResult_Adventure',
    'UI_GameResult_AncientTower',
    'UI_GameResult_NestDungeon',
    'UI_GameResult_SecretDungeon',
    'UI_GamePause',
    'UI_GamePause_AncientTower',
    'UI_GamePause_NestDungeon',
    'UI_GamePause_SecretDungeon',
    'UI_GamePause_Colosseum',
	'UI_GameDPSPopup',
	'UI_GameDPSListItem',
    'UI_GameDebug',
    'UI_GameDebug_InfoPopup',
	'UI_GameDebug_RealTime',
    'UI_IngameDragonPanel',
    'UI_IngameDragonPanelItem',
    'UI_IngameTamerPanelItem',
    'UI_IngameUnitInfo',
    'UI_IngameDragonInfo',
    'UI_IngameBossInfo',
    'UI_AutoPlaySettingPopup',

	-- UI : 가방
    'UI_Inventory',
    'UI_InventorySelectSellItems',
    'UI_InventoryTab',
    'UI_InventoryTabRune',
    'UI_InventoryTabFruit',
    'UI_InventoryTabEvolutionStone',
    'UI_InventorySellItems',
    'UI_RuneBulkSalePopup',
    'UI_EvolutionStoneCombine',
    'UI_EvolutionStoneCombineListItem',

	-- UI : 각종 랭킹
    'UI_RecommendedDragonInfoPopup',
	'UI_RecommendedDragonInfoListItem_Dungeon',
	'UI_RecommendedDragonInfoListItem_Dragon',
	'UI_RecommendedDragonInfoListItem_Party',
	'UI_OverallRankingPopup',
	'UI_OverallRankingListItem',

    -- UI : 도감 관련
	'UI_Book',
	'UI_BookDetailPopup',

    -- UI : 친구 시스템 관련
    'UI_FriendPopup',
    'UI_FriendPopupTab',
    'UI_FriendPopupTabFriends',
    'UI_FriendPopupTabRecommend',
    'UI_FriendPopupTabRequest',
    'UI_FriendPopupTabResponse',
    'UI_FriendListItem',
    'UI_FriendRecommendUserListItem',
    'UI_FriendRequestListItem',
    'UI_FriendResponseListItem',

    -- UI : 드래곤 관리 관련
    'UI_DragonManage_Base',
    'UI_DragonManageInfo',
    'UI_DragonLevelUp',
    'UI_DragonLevelUpHelper',
    'UI_DragonUpgrade',
	'UI_DragonSkillEnhance',
    'UI_DragonEvolution',
    'UI_SkillDetailPopup',
    'UI_DragonRunes',
    'UI_DragonRunesEnhance',
    'UI_DragonFriendship', 
	'UI_DragonSell',

	-- UI : 드래곤 관리 - 결과
    'UI_DragonManageFriendshipResult',
    'UI_DragonEvolutionResult',
    'UI_DragonUpgradeResult',
    'UI_DragonLevelupResult',
	'UI_DragonSkillEnhance_Result',

	-- UI : 드래곤 평가
	'UI_DragonBoardPopup',
	'UI_DragonBoardListItem',
	'UI_DragonBoardPopup_Evaluate',
	'UI_DragonBoardPopup_Write',

	-- UI : 테이머 관리
	'UI_TamerManagePopup',
    'UI_TamerManagePopup_Colosseum',
    'UI_TamerManageItem',
	'UI_SkillDetailPopup_Tamer',
    'UI_SkillDetailPopupListItem_Tamer',
	'UI_SkillEnhance',

	-- UI: 유저 상세 정보
	'UI_UserInfoDetailPopup',
	'UI_UserInfoDetailPopup_SetLeader',
    'UI_UserInfoDetailPopup_SetTitle',

	-- UI : 출석 이벤트
    'UI_AttendanceBasicListItem',
    'UI_AttendanceSpecialListItem',


    -- UI : 탐험(exploration)
    'UI_Exploration',
    'UI_ExplorationIng',
    'UI_ExplorationLocationButton',
    'UI_ExplorationReady',
    'UI_ExplorationResultPopup',

    -- UI : EVENT
    'UI_EventPopup',
    'UI_EventPopupTabButton',
    'UI_EventPopupTab_Attendance',
    'UI_EventPopupTab_EventAttendance',
    'UI_EventPopupTab_AccessTime',
    'UI_EventPopupTab_Banner',
    'UI_EventPopupTab_Shop',
    'UI_EventPopupTab_Notice',
    'UI_EventPopupTab_HBShop',
    'UI_EventPopupTab_HBShop_Coupon',
    'UI_ExchangeProductListItem',
    'UI_AccessTimeDataListItem',

	-- UI : 연출
	'DirectingCharacter',

	-- UI : 채팅
	'UI_ChatPopup',
    'UI_ChatPopup_WhisperTab',
    'UI_ChatList',
    'UI_ChatListItem',
    'UI_ChatListItem_msg',
    'UI_ChatListItem_myMsg',
    'UI_ChatListItem_systemMsg',
    'UI_ChatIgnoreListItem',

	-- UI : 설정
	'UI_Setting',
    'UI_SettingAccountTab',
    'UI_SettingDevTab',
    'UI_SettingGameTab',
    'UI_SettingInfoTab',
    'UI_DragonDevApiPopup',
    'UI_InvenDevApiPopup',

    -- Tutorial
    'UI_TutorialPlayer',
    'TutorialManager',
    'TutorialHelper',

    -- Network
    'Network',
    'socket',

    -- UI : Generated
}

-------------------------------------
-- function loadModule
-------------------------------------
function loadModule()
	-- penlight lua 라이브러리
    pl = require 'pl.import_into'()
    csv = require 'perpleLib/lua_csv'

    for i,v in ipairs(t_module) do
        require(v)
    end
end

local t_except_reload = {
    ['SoundMgr'] = true,
    ['uilib/UIManager'] = true,
    ['uilib/UILoader'] = true,
    ['uilib/TableView'] = true,
    ['socket'] = true,
}
-------------------------------------
-- function reloadModule
-------------------------------------
function reloadModule()
    print('#############################')
    print('## reloadModule() start    ##')

    -- 서버에서 받아서 저장 중인 테이블 백업
    local t_backup_server_table = TABLE:backupServerTable()

    for i,v in ipairs(t_module) do
        if not (t_except_reload[v]) then
            package.loaded[v] = nil
            require(v)
        end
    end

    TABLE:init()
	g_constant:readDataFile()

    -- 서버에서 받아서 저장 중인 테이블 적용
    for i,v in pairs(t_backup_server_table) do
        TABLE[i] = v
    end
    print('## reloadModule() end      ##')
    print('#############################')
end