# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

target 'sdk_binder' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    project 'sdk_binder'

    # Pods for Firebase
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics', '8.1.0'
    
    ## SOCIAL
    # Pods for Google
    pod 'GoogleSignIn', '5.0.2'
    
    # Pods for Facebook
    # https://developers.facebook.com/docs/ios/
    # sgkim 2019.10.11 (4.39.1 -> 5.8.0)
    pod 'FBSDKCoreKit', '9.1.0'
    pod 'FBSDKShareKit', '9.1.0'
    pod 'FBSDKLoginKit', '9.1.0'
    
    # Pods for Twitter
    pod 'TwitterKit'#, '= 3.4.2'

    ## ADS
    # Pods for AdMob
    pod 'Google-Mobile-Ads-SDK'#, '= 7.50.0'
    # pod 'GoogleMobileAdsMediationUnity'#, '= 3.0.0.3'
    # AdColony 4.1.1에 해당하는 AdMob SDK 버전이 없어서 미디에이션에서 제외
    # https://cocoapods.org/pods/GoogleMobileAdsMediationAdColony
    # pod 'GoogleMobileAdsMediationAdColony'#, '= 3.3.6.0'
    # pod 'GoogleMobileAdsMediationTapjoy'#, '=12.3.3.0'
    # Pods for UnityAds
    # pod 'UnityAds'#, '= 3.0.0'
    
    # Pods for AdColony
    # https://github.com/AdColony/AdColony-iOS-SDK
    # https://github.com/AdColony/AdColony-iOS-SDK/blob/master/CHANGELOG.md
    # sgkim 2019.10.14 (3.3.6 -> 4.1.1)
    pod 'AdColony'#, '= 4.1.1'
    pod 'GoogleUserMessagingPlatform', '~> 2.1.0'


    ## STATISTIC
    
    # Pods for IGAWorks
    #pod 'IgaworksCore', '= 2.4.8'
    #pod 'AdBrix', '= 2.2.8'
    # @sgkim 20190919 adbrix 정책 변경으로 인해 더이상 사용하지 않게되어 제거

    # @kyhwang 20230926 tapjoy analytics 지원 중단으로 인해 제거
    # pod 'TapjoySDK'
    # Pods for Adjust
    pod 'Adjust', '4.29.6'
end


