# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'DragonVillageM iOS' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for DragonVillageM iOS
    
    # Pods for Firebase
    pod 'Firebase/Core', '= 5.15.0'
    pod 'Firebase/Auth', '= 5.15.0'
    pod 'Firebase/Messaging', '= 5.15.0'

    # Pods for Crashlytics
    pod 'Fabric', '= 1.9.0'
    pod 'Crashlytics', '= 3.12.0'
    
    ## SOCIAL
    # Pods for Google
    pod 'GoogleSignIn', '= 4.4.0'
    # Pods for Facebook
    pod 'FBSDKCoreKit', '= 4.39.1'
    pod 'FBSDKShareKit', '= 4.39.1'
    pod 'FBSDKLoginKit', '= 4.39.1'
    # Pods for Twitter
    pod 'TwitterKit', '= 3.4.2'

    ## ADS
    # Pods for AdMob
    pod 'Google-Mobile-Ads-SDK', '= 7.37.0'
    pod 'GoogleMobileAdsMediationUnity', '= 3.0.0.0'
    pod 'GoogleMobileAdsMediationAdColony', '= 3.3.6.0'
    # Pods for UnityAds
    pod 'UnityAds', '= 3.0.0'
    # Pods for AdColony
    pod 'AdColony', '= 3.3.6'


    ## STATISTIC
    
    # Pods for IGAWorks
    #pod 'IgaworksCore', '= 2.4.8'
    #pod 'AdBrix', '= 2.2.8'
    # @sgkim 20190919 adbrix 정책 변경으로 인해 더이상 사용하지 않게되어 제거

    # Pods for Tapjoy
    pod 'TapjoySDK', '= 12.2.0'
    # Pods for Adjust
    pod 'Adjust', '= 4.17.1'
end

target 'DragonVillageM Mac' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for DragonVillageM Mac
end
