# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'DragonVillageM iOS' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for DragonVillageM iOS
    
    # Pods for Firebase
    pod 'Firebase/Core'#, '= 6.10.0'
    pod 'Firebase/Auth'#, '= 6.10.0'
    pod 'Firebase/Messaging'#, '= 6.10.0'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    
    ## SOCIAL
    # Pods for Google
    pod 'GoogleSignIn'#, '= 5.0.1'
    
    # Pods for Facebook
    # https://developers.facebook.com/docs/ios/
    # sgkim 2019.10.11 (4.39.1 -> 5.8.0)
    pod 'FBSDKCoreKit'#, '= 5.8.0'
    pod 'FBSDKShareKit'#, '= 5.8.0'
    pod 'FBSDKLoginKit'#, '= 5.8.0'
    
    # Pods for Twitter
    pod 'TwitterKit'#, '= 3.4.2'

    ## ADS
    # Pods for AdMob
    pod 'Google-Mobile-Ads-SDK'#, '= 7.50.0'
    pod 'GoogleMobileAdsMediationUnity'#, '= 3.0.0.3'
    #AdColony 4.1.1에 해당하는 AdMob SDK 버전이 없어서 미디에이션에서 제외
    # https://cocoapods.org/pods/GoogleMobileAdsMediationAdColony
    #pod 'GoogleMobileAdsMediationAdColony'#, '= 3.3.6.0'
    #pod 'GoogleMobileAdsMediationTapjoy'#, '=12.3.3.0'
    # Pods for UnityAds
    pod 'UnityAds'#, '= 3.0.0'
    
    # Pods for AdColony
    # https://github.com/AdColony/AdColony-iOS-SDK
    # https://github.com/AdColony/AdColony-iOS-SDK/blob/master/CHANGELOG.md
    # sgkim 2019.10.14 (3.3.6 -> 4.1.1)
    pod 'AdColony'#, '= 4.1.1'


    ## STATISTIC
    
    # Pods for IGAWorks
    #pod 'IgaworksCore', '= 2.4.8'
    #pod 'AdBrix', '= 2.2.8'
    # @sgkim 20190919 adbrix 정책 변경으로 인해 더이상 사용하지 않게되어 제거

    # Pods for Tapjoy
    pod 'TapjoySDK'#, '= 12.3.3'
    # Pods for Adjust
    pod 'Adjust'#, '= 4.17.1'
end

target 'DragonVillageM Mac' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for DragonVillageM Mac
end
