# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'DragonVillageT iOS' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DragonVillageT iOS

  # Pods for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'

  # Pods for Google
  pod 'GoogleSignIn'

  # Pods for Facebook
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  # Pods for IGAWorks
  pod 'IgaworksCore'
  pod 'AdBrix'

end

target 'DragonVillageT Mac' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DragonVillageT Mac

end
